Repository ChainSafe/gossamer, pull requests merged in 2019-11, with the labels that each got.

#368 p2p: Seperate host
  cmd/netsim/main.go
  cmd/netsim/sim.go
  p2p/bootstrap.go
  p2p/host.go
  p2p/notifee.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Needs Review

#371 SCALE Updates
  codec/decode.go
  codec/enc_dec_test.go
  codec/encode.go
  codec/encode_test.go
Labels: Status: Needs Review

#369 cmd, p2p, trie: load p2p data from genesis
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis_test.go
  common/common.go
  genesis.json
  p2p/config.go
  p2p/connmgr.go
  p2p/host.go
  polkadb/dbService.go
  trie/database.go
  trie/database_test.go
Labels: Status: Needs Changes, Status: Needs Review, startup & genesis

#374 cmd, codec, config, trie: ignore unexported struct fields, change trie.Genesis to genesis.GenesisData
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  codec/decode.go
  codec/encode.go
  config/genesis/genesis.go
  trie/database.go
  trie/database_test.go
Labels: Status: Needs Review

#392 Update Readme
  README.md
Labels: Status: Needs Review

#343 [consensus/babe, core/blocktree]: slot time calculation
  consensus/babe/babe_slots.go
  consensus/babe/babe_test.go
  core/blocktree/blocktree.go
  core/blocktree/blocktree_test.go
  core/blocktree/node.go
  core/types/types.go
Labels: Status: Merge Ready

#393 crypto, keystore: encrypt/decrypt private keys, read/writes to file
  crypto/ed25519.go
  crypto/ed25519_test.go
  crypto/keypair.go
  keystore/keystore.go
  keystore/keystore_test.go
Labels: Status: Needs Changes

#396 common,runtime, babe, core: Runtime Call Safety
  common/transaction/priority_queue.go
  common/transaction/priority_queue_test.go
  consensus/babe/runtime.go
  core/runtime.go
  runtime/wasmer.go
  runtime/wasmer_test.go
  scripts/ci.sh
Labels: Status: Needs Review

#403 p2p: use p2p instead of ipfs for host multiaddress
  p2p/host.go
Labels: Status: Needs Review

#363 p2p, core, babe: Channel from babe to p2p service
  cmd/gossamer/configcmd.go
  consensus/babe/babe.go
  consensus/babe/babe_slots.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  core/service.go
  core/service_test.go
  dot/dot_test.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Merge Ready

#413 p2p: add connect/disconnect handlers to connection manager
  go.sum
  p2p/connmgr.go
Labels: Status: Needs Review

#412 Remove CLI Flag Migration
  cmd/gossamer/main.go
Labels: Status: Merge Ready

#414 p2p: update to latest go-libp2p packages
  go.mod
  go.sum
  p2p/host.go
Labels: Status: Merge Ready

#405 cmd, crypto, keystore: add account subcommand and key generation functionality
  cmd/gossamer/account.go
  cmd/gossamer/account_test.go
  cmd/gossamer/configcmd.go
  cmd/gossamer/main.go
  cmd/utils/flags.go
  crypto/ed25519.go
  crypto/keypair.go
  crypto/sr25519.go
  go.mod
  go.sum
  keystore/keystore.go
  keystore/keystore_test.go
Labels: Status: Needs Review

#407 main, core: Core instantiate babe
  cmd/gossamer/configcmd.go
  common/types.go
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  core/blocktree/blocktree_test.go
  core/blocktree/node.go
  core/rawdb/rawdb.go
  core/rawdb/rawdb_test.go
  core/service.go
  core/service_test.go
  core/types/types.go
  p2p/message.go
Labels: Status: Needs Review

#415 p2p: refactor and add checks to p2p tests
  p2p/config_test.go
  p2p/p2p_test.go
Labels: Status: Merge Ready

#420 crypto, keystore, runtime: implement ext_sr25519_generate, ext_sr25519_verify, ext_ed25519_generate
  cmd/gossamer/configcmd.go
  common/types.go
  consensus/babe/babe_test.go
  core/service_test.go
  crypto/ed25519.go
  crypto/keypair.go
  crypto/sr25519.go
  crypto/sr25519_test.go
  go.mod
  go.sum
  keystore/encrypt.go
  keystore/encrypt_test.go
  keystore/keystore.go
  keystore/keystore_test.go
  runtime/imports.go
  runtime/wasmer.go
  runtime/wasmer_test.go
Labels: Status: Needs Review

#422 babe,core,runtime: Fixes Add Constants For Runtime Calls #401
  consensus/babe/babe.go
  consensus/babe/runtime.go
  core/runtime.go
  runtime/types.go
  runtime/wasmer_test.go
Labels: Status: Needs Review

#426 trie: add child storage support
  trie/child_storage.go
  trie/child_storage_test.go
  trie/trie.go
  trie/trie_test.go
Labels: Status: Merge Ready

#409 CI enhancements - Update Dockerfile to working version, update build+fmt+imports
  .gitignore
  .travis.yml
  Dockerfile.dev
  Makefile
  README.md
  p2p/config.go
  p2p/host.go
  scripts/ci.go
  scripts/docker-entrypoint.sh
  scripts/goimports.sh
Labels: Status: Merge Ready
