Repository ChainSafe/gossamer, pull requests merged in 2019-12, with the labels that each got.

#434 runtime: ext_ child storage
  runtime/imports.go
  runtime/wasmer_test.go
Labels: Status: Needs Review

#435 allocator: Update alloctator logs
  runtime/allocator/allocator.go
  runtime/allocator/allocator_test.go
Labels: Status: Merge Ready

#433 crypto, runtime: ext_ public keys, sign
  crypto/ed25519.go
  crypto/sr25519.go
  keystore/keystore.go
  runtime/imports.go
  runtime/wasmer.go
  runtime/wasmer_test.go
Labels: Status: Needs Changes

#427 p2p: add foundation for status message exchange
  go.sum
  p2p/config.go
  p2p/connmgr.go
  p2p/host.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Needs Review

#446 cmd, core, consensus/babe: add configs for core.Service, babe.Session, add keystore
  cmd/gossamer/configcmd.go
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  consensus/babe/types.go
  core/service.go
  core/service_test.go
Labels: Status: Merge Ready

#451 grandpa: add types
  cmd/gossamer/main.go
  consensus/grandpa/types.go
Labels: Status: Needs Changes

#452 runtime: scale encode key values in enumerated_trie_root
  runtime/imports.go
  runtime/wasmer_test.go
Labels: Status: Merge Ready

#440 state: State refactor
  state/block.go
  state/interface.go
  state/network.go
  state/service.go
  state/storage.go
Labels: Status: Merge Ready

#471 refactor(runtime): Update wasmer & remove Registry
  go.mod
  go.sum
  runtime/allocator/allocator_test.go
  runtime/imports.go
  runtime/wasmer.go
Labels: Status: Merge Ready

#456 p2p: migrate gossip logic
  p2p/gossip.go
  p2p/host.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Needs Review

#470 crypto, keypair: move keys to subpackages
  cmd/gossamer/account.go
  consensus/babe/types.go
  crypto/ed25519.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/ed25519_test.go
  crypto/keypair.go
  crypto/sr25519/sr25519.go
  crypto/sr25519/sr25519_test.go
  keystore/encrypt.go
  keystore/encrypt_test.go
  keystore/keystore.go
  keystore/keystore_test.go
  runtime/imports.go
  runtime/wasmer_test.go
Labels: Status: Merge Ready

#477 Finish Badger Migration
  cmd/gossamer/configcmd_test.go
  go.mod
  go.sum
  polkadb/database.go
  polkadb/database_test.go
  runtime/wasmer.go
Labels: Status: Merge Ready

#472 crypto: implement secp256k1 keys
  crypto/ed25519/ed25519.go
  crypto/ed25519/ed25519_test.go
  crypto/keypair.go
  crypto/secp256k1/secp256k1.go
  crypto/secp256k1/secp256k1_test.go
  crypto/sr25519/sr25519.go
  crypto/sr25519/sr25519_test.go
  keystore/encrypt.go
  keystore/encrypt_test.go
  keystore/keystore.go
  keystore/keystore_test.go
  runtime/imports.go
  runtime/wasmer_test.go
Labels: Status: Needs Review

#483 state: GetLatestBlock
  state/block.go
Labels: Status: Merge Ready

#476 state, cmd, polkadb, dot: Move DBs to State Service
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  dot/dot_test.go
  polkadb/database_test.go
  polkadb/dbService.go
  polkadb/table_test.go
  state/block.go
  state/service.go
  state/service_test.go
  state/storage.go
Labels: Status: Merge Ready

#479 cmd: simplify TestMakeNode
  cmd/gossamer/configcmd_test.go
Labels: Status: Merge Ready

#481 cmd, common, crypto, keystore: unlock keys by command line
  cmd/gossamer/account.go
  cmd/gossamer/account_test.go
  cmd/gossamer/configcmd.go
  cmd/gossamer/main.go
  cmd/gossamer/unlock.go
  cmd/gossamer/unlock_test.go
  cmd/utils/flags.go
  common/common.go
  common/common_test.go
  crypto/ed25519/ed25519.go
  crypto/secp256k1/secp256k1.go
  crypto/sr25519/sr25519.go
  keystore/encrypt.go
  keystore/helpers.go
  keystore/keystore.go
Labels: Status: Merge Ready

#486 cmd: Providing bootnodes should disable default bootnodes
  cmd/gossamer/configcmd.go
Labels: Status: Needs Changes

#492 main: Fixed retrieval of genesisflag from utils.
  cmd/gossamer/genesis.go
Labels: Status: Needs Review

#491 runtime, state, core, consensus, cmd: Migrate runtime calls
  cmd/gossamer/configcmd.go
  consensus/babe/babe_test.go
  core/service_test.go
  runtime/imports.go
  runtime/interface.go
  runtime/wasmer.go
  runtime/wasmer_test.go
  state/service.go
  state/storage.go
Labels: Status: Merge Ready

#489 core, p2p: status validation and expiration
  core/service.go
  p2p/discovery.go
  p2p/host.go
  p2p/p2p.go
  p2p/status.go
  p2p/status_test.go
  p2p/types.go
Labels: Status: Needs Review

#497 Update README.md
  README.md
Labels: Status: Merge Ready

#490 p2p: update configuration and host
  go.sum
  p2p/config.go
  p2p/config_test.go
  p2p/gossip.go
  p2p/gossip_test.go
  p2p/host.go
  p2p/host_test.go
  p2p/mdns.go
  p2p/mdns_test.go
  p2p/service.go
  p2p/service_test.go
  p2p/status.go
  p2p/status_test.go
  p2p/types.go
  p2p/utils.go
  p2p/utils_test.go
Labels: Status: Merge Ready

#498 cmd: Genesis Init Failure Fix
  cmd/gossamer/genesis.go
Labels: Status: Merge Ready

#505 Update Makefile
  Makefile
Labels: Status: Merge Ready

#499 consensus/babe, runtime: fix ext_get_allocated_storage, implement build-block for empty block
  common/transaction/types.go
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  consensus/babe/types.go
  core/blocktree/blocktree.go
  core/blocktree/blocktree_test.go
  core/blocktree/node.go
  core/service.go
  core/service_test.go
  core/types/types.go
  runtime/imports.go
  runtime/types.go
  runtime/wasmer_test.go
  state/block.go
Labels: Status: Needs Review
