Repository ChainSafe/gossamer, pull requests merged in 2019-03, with the labels that each got.

#41 Export reader and writer
  codec/decode.go
  codec/encode.go
Labels: bug

#46 BadgerDB Basic Ops
  polkadb/database.go
  polkadb/database_test.go
  polkadb/interface.go
Labels: DB

#59 Amer/encode strings
  codec/encode_test.go
Labels: SCALE

#77 Dependency management: dep
  Gopkg.lock
  Gopkg.toml
Labels: enhancement

#71 BadgerDB: Batch and Iterator Functionality
  polkadb/database.go
  polkadb/database_test.go
  polkadb/interface.go
Labels: DB
