Repository ChainSafe/gossamer, pull requests merged in 2019-10, with the labels that each got.

#320 p2p: Daniel/gossiping
  go.mod
  go.sum
  p2p/message.go
  p2p/message_test.go
  p2p/p2p.go
  p2p/p2p_test.go
  runtime/imports.go
Labels: Status: Merge Ready

#330 cmd,config,p2p: Minor Fixes
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/main.go
  cmd/netsim/sim.go
  cmd/utils/flags.go
  config/defaults.go
  go.mod
  p2p/bootstrap.go
  p2p/config.go
  p2p/p2p.go
  polkadb/blockDB.go
  polkadb/database.go
  polkadb/dbService.go
  polkadb/stateDB.go
Labels: Status: Needs Changes

#321 core, cmd, p2p: process transaction message
  cmd/gossamer/configcmd.go
  common/transaction/priority_queue.go
  common/transaction/priority_queue_test.go
  core/service.go
  core/service_test.go
  p2p/config.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Merge Ready

#333 core: process block
  core/service.go
  core/service_test.go
Labels: Status: Needs Changes, Status: Needs Review

#340 Added license header to missing files
  cmd/gossamer/configcmd.go
  common/optional/types.go
  common/transaction/priority_queue.go
  common/transaction/priority_queue_test.go
  common/transaction/types.go
  core/runtime.go
  p2p/config.go
  polkadb/blockDB.go
  polkadb/dbService.go
  polkadb/dbService_test.go
  polkadb/stateDB.go
  polkadb/table.go
  polkadb/table_test.go
Labels: Status: Merge Ready

#334 Services Updates
  .gitignore
  cmd/gossamer/configcmd.go
  cmd/netsim/main.go
  core/service.go
  core/service_test.go
  dot/dot_test.go
  internal/api/api.go
  internal/services/services.go
  internal/services/services_test.go
  p2p/bootstrap_test.go
  p2p/p2p.go
  p2p/p2p_test.go
  polkadb/database_test.go
  polkadb/dbService.go
  polkadb/dbService_test.go
  polkadb/table_test.go
Labels: Status: Merge Ready

#332 [core/rawdb, types, interface, common] Initial Block Operations
  .travis.yml
  cmd/netsim/main.go
  common/common.go
  core/blocktree/blocktree.go
  core/blocktree/blocktree_test.go
  core/rawdb/rawdb.go
  core/rawdb/rawdb_test.go
  core/rawdb/schema.go
  core/service.go
  core/types/types.go
  internal/services/services.go
  internal/services/services_test.go
  polkadb/dbService.go
  polkadb/interface.go
Labels: Status: Needs Review

#323 config, cmd: read genesis file
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/main.go
  cmd/utils/flags.go
  config.toml
  config/defaults.go
  config/genesis/genesis.go
  config/genesis/genesis_test.go
  genesis.json
Labels: Status: Merge Ready

#341 Reduce DB Test Iterations
  polkadb/database_test.go
  polkadb/table_test.go
Labels: Status: Needs Review

#342 Config/CLI Maintenance
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/main.go
  cmd/netsim/sim.go
  cmd/utils/flags.go
  config/config.go
  config/defaults.go
  dot/dot.go
  dot/dot_test.go
  p2p/config.go
  rpc/http.go
Labels: Status: Needs Changes, Status: Needs Review

#348 p2p: Save ID Key
  .gitignore
  .travis.yml
  p2p/bootstrap_test.go
  p2p/config.go
  p2p/p2p_test.go
Labels: Status: Merge Ready

#345 consensus/babe: start function
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/types.go
Labels: Status: Merge Ready

#350 p2p: Simplify Bootstrap
  cmd/gossamer/configcmd.go
  go.mod
  p2p/address_utils_test.go
  p2p/bootstrap.go
  p2p/bootstrap_test.go
  p2p/config.go
  p2p/config_test.go
  p2p/p2p.go
  p2p/p2p_test.go
Labels: Status: Needs Changes

#352 trie: encode and decode trie for DB, save and load to/from DB
  trie/database.go
  trie/database_test.go
  trie/node.go
  trie/node_test.go
  trie/print.go
  trie/trie.go
  trie/trie_test.go
Labels: Status: Needs Changes

#355 cmd,config,dot,rpc: Decouple configs
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  config.toml
  config/config.go
  config/defaults.go
  dot/dot_test.go
  rpc/http.go
Labels: Status: Needs Review

#358 runtime: Runtime Logs
  runtime/imports.go
Labels: Status: Needs Review

#349 cmd, config, p2p: Add Global Config
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/main.go
  cmd/utils/flags.go
  config.toml
  config/config.go
  config/defaults.go
  go.mod
  go.sum
  p2p/config.go
  p2p/p2p_test.go
Labels: Status: Needs Review

#362 Change P2P Key Type & Encoding
  p2p/config.go
Labels: Status: Merge Ready

#344 cmd, config, runtime, trie: load genesis state into storage trie and load `:code`
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  cmd/gossamer/main.go
  codec/decode.go
  config/genesis/genesis.go
  config/genesis/genesis_test.go
  consensus/babe/babe_test.go
  core/service.go
  core/service_test.go
  dot/dot.go
  dot/dot_test.go
  genesis.json
  polkadb/dbService.go
  runtime/wasmer.go
  runtime/wasmer_test.go
  trie/database.go
  trie/database_test.go
  trie/trie.go
  trie/trie_test.go
Labels: Status: Needs Review, startup & genesis
