Repository ChainSafe/gossamer, pull requests merged in 2019-04, with the labels that each got.

#96 Elizabeth/trie simplify
  .golangci.yml
  common/common.go
  common/common_test.go
  polkadb/memoryDB.go
  polkadb/memoryDB_test.go
  trie/codec.go
  trie/codec_test.go
  trie/database.go
  trie/iterator.go
  trie/node.go
  trie/node_test.go
  trie/trie.go
  trie/trie_test.go
Labels: Waiting For Review

#102 log15 package added
  go.mod
  go.sum
Labels: enhancement

#108 Fixed p2p TestStringsToPeerInfos test
  p2p/bootstrap_test.go
Labels: tests
