Repository ChainSafe/gossamer, pull requests merged in 2020-04, with the labels that each got.

#732 lib/blocktree: update leafmap to sync.Map
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/database.go
  lib/blocktree/database_test.go
  lib/blocktree/leaves.go
Labels: Status: Approved

#726 dot/core, lib/blocktree, lib/database: create error definitions
  dot/core/errors.go
  dot/core/runtime.go
  dot/core/service.go
  dot/core/sync.go
  lib/blocktree/blocktree.go
  lib/blocktree/database.go
  lib/blocktree/errors.go
  lib/blocktree/node.go
  lib/database/errors.go
  lib/database/memoryDB.go
Labels: Status: Approved

#737 dot/rpc: Introduce Gorilla RPC package
  dot/rpc/dot_up_codec.go
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/json2/client.go
  dot/rpc/json2/error.go
  dot/rpc/json2/server.go
  dot/rpc/json2/server_test.go
  dot/rpc/server.go
  dot/rpc/server_test.go
  dot/rpc/serviceMap.go
  dot/rpc/serviceMap_test.go
  dot/services.go
  go.mod
  go.sum
Labels: Status: Approved

#739 dot/core: fix node stall when syncing
  dot/core/service.go
  dot/core/sync.go
Labels: Status: Approved

#745 dot/rpc: implement RPC methods chain_getHeader and chain_getBlock
  dot/rpc/dot_up_codec.go
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_test.go
  dot/state/block.go
  node/gssmr/config.toml
  node/gssmr/defaults.go
Labels: Status: Approved

#746 dot/core, lib/transaction: remove included extrinsics from queue
  dot/core/service.go
  dot/core/state.go
  dot/core/sync.go
  dot/core/sync_test.go
  dot/core/types/types.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/state/tx_queue.go
  lib/babe/build.go
  lib/babe/state.go
  lib/transaction/priority_queue.go
  lib/transaction/priority_queue_test.go
Labels: Status: Needs Review

#742 cmd: use subcommand specific flags
  cmd/gossamer/account.go
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  dot/config.go
  dot/config_test.go
  dot/genesis_test.go
  dot/node.go
  dot/node_test.go
  dot/services.go
  dot/services_test.go
  dot/utils.go
  lib/keystore/keystore_test.go
  lib/utils/utils.go
  node/gssmr/config.toml
  node/ksmcc/config.toml
Labels: Status: Needs Review

#754 docs: fix assets path in README
  README.md
Labels: Status: Needs Review

#752 dot/rpc; implement RPC chain_getBlockHash
  dot/rpc/http_test.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_test.go
Labels: Status: Approved

#715 dot/core: call core execute block
  dot/core/runtime.go
  dot/core/runtime_test.go
  dot/core/syncer.go
  dot/core/syncer_test.go
  lib/runtime/imports.go
  node/gssmr/config.toml
Labels: Status: Approved, Status: BLOCKED

#733 cmd, dot: overwrite config with genesis
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/flags.go
  dot/config.go
  dot/config_test.go
  dot/utils.go
  node/gssmr/config.toml
  node/gssmr/defaults.go
  node/ksmcc/config.toml
  node/ksmcc/defaults.go
Labels: Status: Needs Review

#747 lib/runtime: isolate runtime updates
  dot/core/messages_test.go
  dot/core/runtime_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/syncer_test.go
  dot/genesis_test.go
  dot/services.go
  go.mod
  go.sum
  lib/babe/babe_test.go
  lib/babe/runtime.go
  lib/babe/runtime_test.go
  lib/runtime/allocator.go
  lib/runtime/allocator_test.go
  lib/runtime/imports.go
  lib/runtime/imports_test.go
  lib/runtime/runtime.go
  lib/runtime/runtime_test.go
  lib/runtime/test_helpers.go
  lib/runtime/wasmer_test_func.go
Labels: Status: Approved

#743 dot/rpc, tests: Add Integration Tests for RPC #741
  .travis.yml
  Makefile
  scripts/integration-test-all.sh
  tests/rpc/empty.go
  tests/rpc/integration_test.go
Labels: Status: Approved

#753 dot, dot/state, lib/genesis: migrate genesis methods
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/main.go
  dot/core/service_test.go
  dot/core/syncer_test.go
  dot/genesis.go
  dot/genesis_test.go
  dot/node.go
  dot/node_test.go
  dot/rpc/modules/chain_test.go
  dot/state/service.go
  dot/state/service_test.go
  dot/utils.go
  lib/babe/babe_test.go
  lib/genesis/genesis.go
  lib/genesis/genesis_test.go
  lib/genesis/helpers.go
  lib/genesis/helpers_test.go
Labels: Status: Approved

#755 dot/core: fix node restart
  dot/core/babe.go
  dot/core/digest.go
  dot/core/digest_test.go
  dot/core/service.go
  dot/core/syncer.go
  dot/network/service.go
  dot/network/status.go
Labels: Status: Approved

#759 lib/database: make the Iterator interface portable
  lib/database/database.go
  lib/database/database_test.go
  lib/database/interface.go
  lib/database/memoryDB.go
  lib/database/table.go
Labels: Status: Approved

#763 lib/database: consolidate Writer interface
  lib/database/database.go
  lib/database/database_test.go
  lib/database/interface.go
  lib/database/memoryDB.go
  lib/database/table.go
  lib/database/table_test.go
Labels: Status: Approved

#761 cmd, dot: load genesis data for initialized node
  .gitignore
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/main.go
  dot/node.go
  dot/utils.go
Labels: Status: Approved

#765 dot/rpc: Implement RPC author_insertKey
  dot/core/messages_test.go
  dot/core/runtime_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/syncer_test.go
  dot/core/test_helpers.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
Labels: Status: Approved

#728 lib/babe: check whether block producer has equivocated
  dot/core/state.go
  dot/state/block.go
  dot/state/block_test.go
  dot/state/service_test.go
  go.mod
  go.sum
  lib/babe/build_test.go
  lib/babe/errors.go
  lib/babe/state.go
  lib/babe/verify.go
  lib/babe/verify_test.go
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/node.go
  lib/crypto/sr25519/sr25519.go
Labels: Status: Approved

#766 dot, lib/database: improve node initialized check
  cmd/gossamer/main.go
  dot/node.go
  dot/node_test.go
  lib/database/database.go
  lib/database/table.go
Labels: Status: Approved

#767 cmd/gossamer: confirm reinitializing a node
  cmd/gossamer/main.go
  cmd/gossamer/utils.go
  cmd/gossamer/utils_test.go
Labels: Status: Needs Review

#771 dot/types, lib/babe/types: migrate babe header to dot types
  dot/core/messages_test.go
  dot/core/runtime_test.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/state/block.go
  dot/types/babe_header.go
  dot/types/babe_header_test.go
  lib/babe/build.go
  lib/babe/verify.go
  lib/scale/decode_ptr_test.go
  tests/babe_test_util.go
Labels: Status: Approved

#769 scripts, tests: Automated Tested of Syncing/Integration with a script #741
  Makefile
  scripts/integration-test-all.sh
  tests/rpc/integration_test.go
Labels: Status: Needs Review

#773 add travis email and slack notifications
  .travis.yml
Labels: Status: Approved

#770 cmd/gossamer: export toml congfiguration file
  cmd/gossamer/account.go
  cmd/gossamer/account_test.go
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  cmd/gossamer/export_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  cmd/gossamer/utils_test.go
  dot/config.go
  dot/node.go
  dot/services.go
  dot/utils.go
Labels: Status: Approved

#783 scripts, tests, rpc: add test for system_networkState
  dot/rpc/http_test.go
  scripts/integration-test-all.sh
  tests/rpc/common.go
  tests/rpc/system_integration_test.go
Labels: Status: Needs Review, rpc, tests

#784 cmd/gossamer: fix and update FixFlagOrder method
  cmd/gossamer/flags.go
  cmd/gossamer/flags_test.go
Labels: Status: Needs Review

#778 dot/core, lib/babe: verify authorship right upon block import
  dot/core/babe.go
  dot/core/babe_test.go
  dot/core/digest.go
  dot/core/digest_test.go
  dot/core/errors.go
  dot/core/messages.go
  dot/core/messages_test.go
  dot/core/runtime_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/syncer.go
  dot/core/syncer_test.go
  dot/core/test_helpers.go
  lib/babe/babe.go
  lib/babe/build_test.go
  lib/babe/errors.go
  lib/babe/types.go
  lib/babe/verify.go
  lib/babe/verify_test.go
  lib/blocktree/blocktree.go
Labels: Status: Needs Review

#785 scripts, tests, rpc: add test for system_peers #741
  tests/rpc/system_integration_test.go
Labels: Status: Needs Review

#788 lib/babe: fix createTestBlock err
  lib/babe/build_test.go
Labels: Status: Approved

#777 dot/rpc: add validity check to RPC author_submitExtrinsic
  dot/core/errors.go
  dot/core/runtime.go
  dot/core/service.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
Labels: Status: Approved

#794 lib/runtime/extrinsic: add extrinsic utils
  lib/runtime/extrinsic/extrinsic.go
  lib/runtime/extrinsic/extrinsic_test.go
Labels: Status: Approved

#797 dot/state: set number to hash mapping for genesis
  dot/state/block.go
Labels: Status: Needs Review

#786 tests: Automated Stress Integration Test for Sync #741
  Makefile
  go.mod
  go.sum
  tests/rpc/common.go
  tests/rpc/empty.go
  tests/rpc/gossamer_utils.go
  tests/rpc/request_utils.go
  tests/rpc/system_integration_test.go
  tests/stress/empty.go
  tests/stress/stress_test.go
Labels: Status: Needs Review

#791 dot, dot/rpc: implement basic websocket support for RPC
  cmd/gossamer/config_test.go
  dot/config.go
  dot/rpc/dot_up_codec.go
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/websocket.go
  dot/rpc/websocket_test.go
  dot/services.go
  dot/utils.go
  go.mod
  go.sum
  node/gssmr/config.toml
  node/gssmr/defaults.go
  node/ksmcc/config.toml
  node/ksmcc/defaults.go
Labels: Status: Needs Review

#806 dot/rpc: implement RPC state_getRuntimeVersion
  dot/core/service.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/websocket.go
  lib/runtime/runtime.go
  lib/runtime/runtime_test.go
  lib/runtime/types.go
  lib/scale/decode_ptr.go
Labels: Status: Needs Review

#805 lib/runtime, lib/babe, dot/core, dot/types: migrate runtime helpers to runtime package
  dot/core/errors.go
  dot/core/messages.go
  dot/core/messages_test.go
  dot/core/runtime.go
  dot/core/runtime_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/node.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
  dot/services.go
  dot/services_test.go
  dot/types/babe.go
  dot/types/babe_test.go
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/build.go
  lib/babe/build_test.go
  lib/babe/inherents_test.go
  lib/babe/runtime.go
  lib/babe/runtime_test.go
  lib/babe/types.go
  lib/babe/types_test.go
  lib/babe/verify.go
  lib/babe/verify_test.go
  lib/runtime/helpers.go
  lib/runtime/helpers_test.go
  lib/runtime/test_helpers.go
Labels: Status: Needs Review

#816 dot/rpc: implement RPC call rpc_methods
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/rpc.go
  dot/rpc/service.go
  dot/rpc/service_test.go
  dot/rpc/websocket_test.go
  dot/services.go
Labels: Status: Needs Review

#795 cmd/gossamer: load default genesis if genesis empty
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export_test.go
  cmd/gossamer/flags.go
  dot/utils.go
  lib/utils/utils.go
Labels: Status: Needs Review

#798 lib/runtime, dot/core, lib/babe: add transaction unit tests
  lib/runtime/extrinsic/extrinsic.go
  lib/runtime/extrinsic/extrinsic_test.go
  lib/runtime/helpers_test.go
  lib/transaction/types.go
  lib/transaction/types_test.go
Labels: Status: Needs Review
