Repository ChainSafe/gossamer, pull requests merged in 2020-01, with the labels that each got.

#493 consensus/babe, state: Babe header type
  consensus/babe/types.go
  state/block.go
Labels: Status: Needs Changes

#502 consensus/babe: block inherents
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/inherents.go
  consensus/babe/types.go
Labels: Status: Needs Review

#509 core/blocktree, core/rawdb, core/types, state: change types.BlockHeader to unexport hash field and add getter/setter
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  core/blocktree/blocktree.go
  core/blocktree/blocktree_test.go
  core/blocktree/node.go
  core/rawdb/rawdb.go
  core/rawdb/rawdb_test.go
  core/types/types.go
  state/block.go
  state/interface.go
Labels: Status: Needs Review

#511 runtime: fix enumerated trie root
  consensus/babe/babe_test.go
  runtime/imports.go
Labels: Status: Merge Ready

#508 consensus/babe, crypto/sr25519, core: add vrf functionality
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  core/service.go
  core/service_test.go
  crypto/sr25519/sr25519.go
  crypto/sr25519/sr25519_test.go
  go.mod
  go.sum
  keystore/keystore.go
Labels: Status: Needs Review

#507 consensus/babe, core, runtime: apply extrinsics
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  core/runtime.go
  core/service_test.go
  runtime/allocator/allocator.go
  runtime/imports.go
  runtime/wasmer.go
  runtime/wasmer_test.go
Labels: Status: Needs Review

#515 consensus/babe, core/types: implement pre-digest and seal for build block
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/types.go
  core/rawdb/rawdb_test.go
  core/types/digest.go
  core/types/types.go
  p2p/message.go
  p2p/message_test.go
Labels: Status: Needs Review

#522 consensus/babe: verify slot winner
  consensus/babe/babe.go
  consensus/babe/types.go
  consensus/babe/verify.go
  consensus/babe/verify_test.go
  crypto/sr25519/sr25519.go
  go.mod
  go.sum
Labels: Status: Needs Review

#478 state: getBlockByNumber
  state/block.go
  state/block_test.go
  state/interface.go
  state/service.go
Labels: Status: Merge Ready

#524 codec: Update scale decoding API
  codec/decode.go
  codec/decode_ptr.go
  codec/decode_ptr_test.go
  codec/decode_test.go
  go.mod
  go.sum
Labels: Status: Merge Ready

#503 state: AddBlock
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  core/blocktree/blocktree_test.go
  core/blocktree/node.go
  core/rawdb/rawdb.go
  core/rawdb/rawdb_test.go
  core/service_test.go
  core/types/types.go
  go.mod
  go.sum
  state/block.go
  state/block_test.go
  state/interface.go
Labels: Status: Needs Review

#534 consensus/babe: verify authorship right
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/types.go
  consensus/babe/types_test.go
  consensus/babe/verify.go
  consensus/babe/verify_test.go
  core/types/digest.go
  core/types/digest_test.go
  go.sum
Labels: Status: Needs Review

#557 cmd, core, consensus/babe: add state interface
  cmd/gossamer/configcmd.go
  consensus/babe/babe.go
  consensus/babe/state.go
  core/rawdb/rawdb.go
  core/rawdb/rawdb_test.go
  core/rawdb/schema.go
  core/service.go
  core/service_test.go
  core/state.go
  runtime/runtime.go
  runtime/runtime_test.go
  state/interface.go
Labels: Status: Needs Review

#560 scale: encode/decode []string in struct
  codec/decode.go
  codec/decode_ptr.go
  codec/encode.go
  codec/encode_test.go
Labels: Status: Needs Review

#558 consensus/babe, core, cmd/gossamer, runtime, runtime/allocator - Move Shared Test Helpers to Package #530
  cmd/gossamer/configcmd_test.go
  consensus/babe/babe_test.go
  consensus/babe/verify_test.go
  core/service_test.go
  runtime/allocator/allocator_test.go
  runtime/runtime_test.go
  runtime/wasmer_test_func.go
  tests/wasmer_test_util.go
Labels: Status: Needs Review

#570 cmd, config: update genesis fields to raw data array
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  config/genesis/genesis.go
  config/genesis/genesis_test.go
  config/gssmr0.json
Labels: Status: Merge Ready

#573 scripts, travis, Fix Docker image and add docker test to Travis build #571
  .travis.yml
  Makefile
  scripts/docker-entrypoint.sh
Labels: Status: Merge Ready

#527 cmd/gossamer, consensus/babe, core, state, trie: state genesis initialization, setup babe from core
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  common/db_keys.go
  common/types.go
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/types.go
  consensus/babe/types/types.go
  consensus/babe/types/types_test.go
  consensus/babe/verify.go
  consensus/babe/verify_test.go
  core/service.go
  core/service_test.go
  dot/dot_test.go
  state/block.go
  state/block_test.go
  state/service.go
  state/service_test.go
  state/storage.go
  trie/database.go
  trie/trie.go
Labels: Status: Needs Review

#555 cmd,trie,polkadb,p2p,config - Cannot handle home dir #496
  Makefile
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  cmd/gossamer/main.go
  cmd/gossamer/unlock_test.go
  cmd/utils/flags.go
  config.toml
  config/config.go
  config/defaults.go
  config/genesis/genesis.go
  config/genesis/genesis_test.go
  p2p/config.go
  p2p/config_test.go
  p2p/gossip_test.go
  p2p/host.go
  p2p/host_test.go
  p2p/service_test.go
  p2p/status_test.go
  polkadb/database.go
  polkadb/table.go
  trie/database_test.go
Labels: Status: Needs Review

#576 consensus/babe, core: initialize new babe session for each epoch
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  core/service.go
  runtime/imports.go
Labels: Status: Needs Review
