Repository ChainSafe/gossamer, pull requests merged in 2020-02, with the labels that each got.

#587 scale: allocate slice elements when decoding
  codec/decode.go
  codec/decode_ptr.go
  codec/decode_test.go
  consensus/babe/babe.go
  consensus/babe/runtime.go
  core/service_test.go
  p2p/message_test.go
Labels: Status: Needs Review

#583 core, core/types, common/optional, state: update BlockData with optional types, add decoding of BlockData to core
  common/common.go
  common/optional/types.go
  common/types.go
  consensus/babe/babe.go
  consensus/babe/state.go
  core/runtime.go
  core/service.go
  core/service_test.go
  core/state.go
  core/types/types.go
  core/types/types_test.go
  p2p/message.go
  p2p/service.go
  p2p/utils.go
  runtime/imports.go
  state/block.go
  state/block_test.go
Labels: Status: Needs Review

#590 consensus/babe, core/types: add block body to block
  .golangci.yml
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  consensus/babe/verify_test.go
  core/types/types.go
  core/types/types_test.go
Labels: Status: Needs Review

#578 state, Thread Safe State Service #550
  .travis.yml
  Makefile
  db/database.go
  state/block.go
  state/block_race_test.go
  state/block_test.go
  state/storage.go
Labels: Status: Merge Ready

#591 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Status: Merge Ready

#597 codec; Enable custom scale methods
  codec/decode_ptr.go
  codec/decode_ptr_test.go
  codec/encode.go
  codec/encode_test.go
  go.mod
Labels: Status: Needs Review

#605 crypto/sr25519: fix NewKeypairFromSeed
  crypto/sr25519/sr25519.go
Labels: Status: Needs Review

#595 consensus/babe, core: read BABE authority updates from block consensus digests
  consensus/babe/babe.go
  consensus/babe/types.go
  consensus/babe/types_test.go
  core/runtime.go
  core/runtime_test.go
  core/service.go
  runtime/types.go
Labels: Status: Needs Review

#607 cmd: update port flag and migrate utils
  cmd/gossamer/account.go
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/genesis.go
  cmd/gossamer/main.go
  cmd/gossamer/unlock.go
Labels: Status: Needs Review

#610 core, consensus/babe, state: block persistence
  common/db_keys.go
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/state.go
  core/service.go
  core/state.go
  state/service.go
  state/storage.go
Labels: Status: Merge Ready

#614 cmd, core: configure whether node is authority
  cmd/gossamer/configcmd.go
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  config.toml
  config/config.go
  config/defaults.go
  core/service.go
  core/service_test.go
Labels: Status: Merge Ready

#603 consensus/babe: load BABE authorities from genesis
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/genesis_test.go
  cmd/gossamer/unlock.go
  codec/decode.go
  codec/decode_ptr.go
  common/common.go
  config/gssmr0.json
  consensus/babe/babe.go
  consensus/babe/babe_test.go
  consensus/babe/runtime.go
  consensus/babe/runtime_test.go
  consensus/babe/types.go
  consensus/babe/types_test.go
  consensus/babe/verify.go
  consensus/babe/verify_test.go
  core/runtime.go
  core/runtime_test.go
  core/service.go
  core/service_test.go
  runtime/wasmer_test_func.go
  tests/babe_test_util.go
Labels: Status: Needs Review

#604 update pending golint issues - #586
  .gitignore
  .golangci.yml
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/genesis.go
  cmd/gossamer/genesis_test.go
  codec/decode.go
  common/db_keys.go
  common/types.go
  config/config.go
  config/genesis/genesis.go
  config/genesis/genesis_test.go
  consensus/babe/babe.go
  consensus/babe/babe_slots.go
  consensus/babe/babe_test.go
  consensus/babe/inherents.go
  consensus/babe/runtime.go
  consensus/babe/runtime_test.go
  consensus/babe/types.go
  core/blocktree/blocktree.go
  core/blocktree/blocktree_test.go
  core/blocktree/leaves.go
  core/blocktree/node.go
  core/service.go
  crypto/sr25519/sr25519.go
  go.mod
  go.sum
  internal/api/api.go
  network/config.go
  network/mdns.go
  network/message.go
  network/state.go
  rpc/json2/error.go
  rpc/json2/server.go
  rpc/modules/author.go
  runtime/imports.go
  runtime/runtime.go
  state/block.go
  state/service.go
  state/storage.go
  tests/babe_test_util.go
  tests/wasmer_test_util.go
  trie/database.go
  trie/database_test.go
  trie/hash.go
  trie/hash_test.go
  trie/node.go
  trie/node_test.go
  trie/print.go
  trie/trie.go
Labels: Status: Code Climate

#625 core, state: store block data after BlockResponseMessage
  common/optional/types.go
  core/service.go
  core/service_test.go
  core/state.go
  network/message.go
  network/message_test.go
  state/block.go
  state/block_test.go
Labels: Status: Needs Review

#630 trie: refactor trie/trie.go methods
  trie/trie.go
Labels: Status: Needs Review

#620 codec; Improve Codec Coverage
  codec/decode.go
  codec/decode_ptr.go
  codec/decode_ptr_test.go
  codec/decode_test.go
  codec/encode.go
  codec/encode_test.go
Labels: Status: Merge Ready

#628 scale: move initialization of large byte arrays
  codec/decode_ptr_test.go
  codec/decode_test.go
Labels: Status: Needs Review

#616 cmd, rpc: remove internal/api, add state service
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  config/config.go
  config/defaults.go
  dot/dot.go
  dot/dot_test.go
  internal/api/api.go
  internal/api/api_test.go
  internal/api/modules/network_module.go
  internal/api/modules/runtime_module.go
  network/config.go
  network/config_test.go
  network/service.go
  network/service_test.go
  network/state.go
  network/state_test.go
  rpc/http.go
  rpc/modules/api.go
  rpc/modules/author.go
  rpc/modules/chain.go
  rpc/modules/state.go
  rpc/modules/system.go
  rpc/modules/system_test.go
  rpc/server.go
  rpc/server_test.go
Labels: Status: Needs Review

#618 core, network: clean up for syncing
  cmd/gossamer/configcmd.go
  consensus/babe/babe.go
  core/runtime.go
  core/service.go
  core/service_test.go
  core/state.go
  network/host.go
  network/message.go
  network/service.go
  network/utils.go
Labels: Status: Needs Review

#606 Request Blocks if needed after Status message exchange #581
  dot/core/block_msg_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/network/status.go
  dot/network/status_test.go
Labels: Status: Merge Ready

#632 db: update log to debug and update messages #418
  lib/database/database.go
  lib/database/table.go
Labels: Status: Needs Review

#631 cmd/gossamer: fix gossamer invalid arguments issue #417
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/gossamer_cmd_test.go
  cmd/gossamer/main.go
  go.mod
  go.sum
Labels: Status: Needs Review

#621 rpc, state: add tx queue to state, implement author_SubmitExtrinsic and author_PendingExtrinsics
  cmd/gossamer/configcmd.go
  dot/core/runtime.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/state.go
  dot/core/types/types.go
  dot/network/service.go
  dot/network/status.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
  dot/rpc/server.go
  dot/state/service.go
  dot/state/tx_queue.go
  go.mod
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/state.go
  lib/common/common.go
  lib/runtime/allocator/allocator.go
  lib/transaction/priority_queue.go
  lib/transaction/priority_queue_test.go
  lib/transaction/types.go
  node/defaults.go
  node/gssmr/config.toml
  node/gssmr/genesis.json
Labels: Status: Needs Review

#633 core/blocktree, consensus/babe: cleanup blocktree, add encode and decode methods
  lib/babe/babe_slots.go
  lib/babe/babe_test.go
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/database.go
  lib/blocktree/database_test.go
  lib/blocktree/leaves.go
  lib/blocktree/node.go
  lib/common/db_keys.go
Labels: Status: Needs Review

#642 state: update state to use one db
  cmd/gossamer/genesis.go
  dot/core/service_test.go
  dot/state/block.go
  dot/state/block_race_test.go
  dot/state/block_test.go
  dot/state/network.go
  dot/state/service.go
  dot/state/storage.go
  scripts/ci.sh
Labels: Status: Needs Review

#643 add keyring package; update gssmr genesis
  dot/core/service.go
  lib/crypto/ed25519/ed25519.go
  lib/crypto/keypair.go
  lib/crypto/secp256k1/secp256k1.go
  lib/crypto/sr25519/sr25519.go
  lib/keyring/keyring.go
  lib/keyring/keyring_test.go
  node/gssmr/genesis.json
Labels: Status: Needs Review

#648 cmd, core: add --key flag to specify test keypair
  cmd/gossamer/configcmd.go
  cmd/gossamer/configcmd_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  dot/core/service.go
  lib/keystore/keystore.go
Labels: Status: Needs Review

#647 state: fix persistence
  dot/core/state.go
  dot/state/block.go
  lib/babe/babe.go
  lib/babe/state.go
Labels: Status: Needs Review

#629 core/blocktree, cmd, core, state, consensus/babe: add blocktree to BlockState, persist blocktree upon restarts
  cmd/gossamer/genesis_test.go
  dot/core/block_msg_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/state.go
  dot/network/mdns.go
  dot/network/service.go
  dot/network/state.go
  dot/network/state_test.go
  dot/state/block.go
  dot/state/block_test.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  lib/babe/babe.go
  lib/babe/babe_slots.go
  lib/babe/babe_test.go
  lib/babe/state.go
  lib/blocktree/blocktree_test.go
  lib/common/db_keys.go
  lib/trie/database.go
Labels: Status: Needs Review
