Repository ChainSafe/gossamer, pull requests merged in 2020-11, with the labels that each got.

#1149 Run intergration tests inside docker containers.
  .travis.yml
  Makefile
Labels: Status: Needs Review, tests

#1151 dot/rpc: Make request parameter for RPC state_getRuntimeVersion a string
  dot/rpc/modules/state.go
Labels: Status: Needs Review, Type: Bug, rpc

#1166 Disable docker for external PRs
  .travis.yml
Labels: tests

#1161 Remove pruned keys from Storage state.
  dot/state/block.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  dot/state/test_helpers.go
Labels: Status: Needs Review

#1178 Updated make file to build on Arch
  Makefile
  go.mod
  go.sum
Labels: Priority: 3 - Medium, Type: Bug
