Repository ChainSafe/gossamer, pull requests merged in 2020-12, with the labels that each got.

#1190 Implement handling of encoded block hash for storage RPC functions
  dot/core/finality_test.go
  dot/core/interface.go
  dot/core/messages_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/rpc/http_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/test_data/expected_metadata
  dot/rpc/websocket_test.go
  dot/state/storage.go
  go.mod
  tests/rpc/rpc_00_test.go
  tests/rpc/rpc_05-state_test.go
Labels: Status: Needs Review

#1217 Parse unstructured array in JSON struct for RPC request.
  dot/rpc/dot_up_codec.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/service_test.go
  go.mod
  go.sum
  lib/common/hash.go
  lib/common/hash_test.go
  packages/rpc/json2/server.go
  tests/rpc/rpc_03-chain_test.go
  tests/rpc/rpc_05-state_test.go
  tests/stress/stress_test.go
Labels: Status: Needs Review

#1223 lib/babe: update verification manager to track changes by epoch
  cmd/gossamer/config.go
  dot/core/digest.go
  dot/node.go
  dot/services.go
  dot/services_test.go
  dot/types/authority.go
  lib/babe/babe.go
  lib/babe/errors.go
  lib/babe/state.go
  lib/babe/types.go
  lib/babe/verify.go
  lib/babe/verify_test.go
Labels: Status: Needs Review

#1227 lib/babe: implement SetOnDisabled; check if authority is disabled when verifying
  dot/core/digest.go
  dot/core/interface.go
  dot/core/test_helpers.go
  dot/sync/interface.go
  dot/sync/syncer.go
  dot/sync/test_helpers.go
  lib/babe/errors.go
  lib/babe/verify.go
  lib/babe/verify_test.go
Labels: Status: Needs Review

#1218 Added EpochLength to config
  chain/gssmr/defaults.go
  chain/ksmcc/defaults.go
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  dot/config.go
  dot/config/toml/config.go
  dot/services.go
  lib/babe/babe.go
  lib/babe/babe_test.go
Labels: Status: Needs Review

#1224 Add validation for JSON RPC params.
  dot/rpc/http.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  go.mod
  go.sum
  lib/common/hash.go
  lib/common/hash_test.go
  tests/rpc/rpc_00_test.go
  tests/rpc/rpc_01-system_test.go
  tests/rpc/rpc_05-state_test.go
  tests/rpc/system_integration_test.go
  tests/stress/helpers.go
  tests/utils/gossamer_utils.go
  tests/utils/system.go
Labels: Status: Needs Review

#1185 lib/grandpa: implement consensus messages using RegisterNotificationsProtocol
  Makefile
  dot/core/finality.go
  dot/core/finality_test.go
  dot/core/interface.go
  dot/core/messages_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/network/gossip.go
  dot/network/gossip_test.go
  dot/network/message.go
  dot/network/message_test.go
  dot/network/notifications.go
  dot/network/service.go
  dot/network/service_test.go
  dot/node.go
  dot/rpc/http_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/system_test.go
  dot/rpc/websocket_test.go
  dot/services.go
  dot/services_test.go
  dot/sync/syncer.go
  lib/babe/babe.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_tracker.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
  tests/stress/grandpa_test.go
  tests/stress/stress_test.go
Labels: Status: Needs Review

#1236 Cleanup peer handshake data on close stream.
  dot/network/connmgr.go
  dot/network/host_test.go
  dot/network/service.go
Labels: Status: Needs Review

#1189 Implement external flags & Local defaults
  chain/gssmr/config.toml
  chain/ksmcc/config.toml
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  cmd/gossamer/flags.go
  docs/pages/Command-Line.md
  dot/build_spec.go
  dot/config.go
  dot/config/toml/config.go
  dot/node.go
  dot/rpc/helpers.go
  dot/rpc/http.go
  dot/rpc/service.go
  dot/rpc/websocket.go
  dot/rpc/websocket_test.go
  dot/services.go
  dot/services_test.go
  go.mod
  go.sum
  tests/utils/gossamer_utils.go
Labels: Priority: 3 - Medium, core

#1202 CMD/Account - Coverage test issue
  .gitignore
  cmd/gossamer/account_test.go
  cmd/gossamer/test_inputs/test-key.key
Labels: Status: Needs Review

#1245 Fix data cleanup during subprotocol close.
  dot/network/connmgr.go
  dot/network/host_test.go
  dot/network/service.go
  go.mod
  go.sum
Labels: Status: Needs Review

#1246 adds github actions ci
  .github/workflows/checks.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  .travis.yml
  Dockerfile
  Makefile
  README.md
  dot/network/host_test.go
  scripts/ci.sh
  tests/stress/grandpa_test.go
Labels: Make travis green again, Type: Maintenance

#1239 test execute_block; re-add to syncer
  dot/core/interface.go
  dot/core/messages_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/node.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/dev_test.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/test_data/expected_metadata
  dot/services.go
  dot/state/block.go
  dot/state/storage_test.go
  dot/state/trie.go
  dot/sync/errors.go
  dot/sync/interface.go
  dot/sync/message.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
  dot/types/block.go
  dot/types/block_test.go
  dot/utils_test.go
  go.mod
  go.sum
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/build.go
  lib/babe/build_test.go
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
  lib/genesis/helpers.go
  lib/runtime/interface.go
  lib/runtime/test_helpers.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmer/test_helpers.go
  lib/trie/trie.go
  lib/trie/trie_test.go
  tests/stress/helpers.go
  tests/stress/stress_test.go
  tests/utils/gossamer_utils.go
Labels: Status: Approved

#1256 Move code coverage into own job + fix ci
  .github/workflows/tests.yml
  README.md
  tests/stress/stress_test.go
Labels: Status: Needs Review, devops

#1242 Implement ext_default functions for v0.8 runtime.
  dot/state/trie.go
  go.sum
  lib/runtime/interface.go
  lib/runtime/test_helpers.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
Labels: Status: Approved

#1234 buildBlockExtrinsics to continue when apply fails
  lib/babe/build.go
Labels: Status: Needs Review

#1240 Updated BABE threshold to be configurable
  chain/gssmr/config.toml
  chain/ksmcc/config.toml
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  dot/config.go
  dot/config/toml/config.go
  dot/core/service.go
  dot/node.go
  dot/node_test.go
  dot/services.go
  dot/services_test.go
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/verify_test.go
  tests/utils/gossamer_utils.go
Labels: Status: Needs Review

#1253 update make lint
  .github/workflows/checks.yml
  Makefile
  dot/network/connmgr.go
  dot/network/utils.go
  dot/rpc/modules/author_test.go
  dot/state/block_notify.go
  dot/state/test_helpers.go
  dot/state/trie.go
  dot/sync/syncer.go
  go.sum
  lib/keystore/helpers.go
  lib/trie/test_utils.go
  scripts/ci.go
  scripts/install-lint.sh
  tests/stress/helpers.go
Labels: Status: Approved, Type: Maintenance

#1244 tests: generate default config in tests
  .gitignore
  go.sum
  lib/runtime/wasmer/instance.go
  tests/rpc/rpc_00_test.go
  tests/stress/grandpa_test.go
  tests/stress/stress_test.go
  tests/utils/gossamer_utils.go
Labels: Status: Approved

#1258 lib/runtime: implement ext_trie_blake2_256_root_version_1; add ext_trie tests
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
Labels: Status: Needs Review

#1192 dot/network: deprecate status messages, remove state.NetworkState
  dot/core/service.go
  dot/core/test_helpers.go
  dot/network/block_announce_test.go
  dot/network/config.go
  dot/network/config_test.go
  dot/network/gossip.go
  dot/network/gossip_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/mdns_test.go
  dot/network/notifications_test.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/state.go
  dot/network/state_test.go
  dot/network/status.go
  dot/network/status_test.go
  dot/network/test_helpers.go
  dot/network/tracker_test.go
  dot/network/transaction_test.go
  dot/rpc/modules/system_test.go
  dot/services.go
  dot/state/network.go
  dot/state/network_test.go
  dot/state/service.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
Labels: Status: Needs Review

#1260 Add git pre-push hook.
  .githooks/pre-push
  Makefile
  go.sum
Labels: Status: Needs Review, Type: Maintenance
