Repository ChainSafe/gossamer, pull requests merged in 2021-04, with the labels that each got.

#1499 feat(dot/network): request block justifications when near head
  dot/network/block_announce.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/notifications.go
  dot/network/service.go
  dot/network/state.go
  dot/network/state_test.go
  dot/network/sync.go
  dot/network/sync_justification.go
  dot/network/sync_justification_test.go
  dot/network/transaction.go
  dot/network/transaction_test.go
  dot/network/utils.go
  dot/rpc/modules/system_test.go
  dot/state/block.go
  dot/state/block_test.go
  dot/sync/syncer.go
  lib/grandpa/network.go
Labels: pr-approved

#1505 chore(codeowners): update codeowners file
  .github/CODEOWNERS
Labels: maintenance, pr-approved

#1506 fix: cmd/gossamer: Generate random name if --name flag not set
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export_test.go
Labels: needs review

#1503 chore(release): Automated release using semantic-release.
  .github/workflows/release.yml
  .releaserc
  package.json
Labels: pr-approved

#1497 feat: dot/telemetry: Implement basic telemetry connection
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/flags.go
  dot/config.go
  dot/node.go
  dot/rpc/modules/api.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  dot/sync/syncer.go
  dot/system/service.go
  dot/system/service_test.go
  dot/telemetry/telemetry.go
  dot/telemetry/telemetry_test.go
  go.mod
  go.sum
  lib/genesis/genesis.go
  lib/genesis/genesis_test.go
  lib/genesis/test_utils.go
Labels: pr-approved

#1507 Fixed edit link
  Makefile
  docs/mkdocs.yml
Labels: chore, pr-approved

#1510 fix(dot/network): fix justification request at head logic
  dot/network/sync_justification.go
Labels: network, pr-approved

#1512 feat(dot/network): implement persistent peers functionality
  cmd/gossamer/config.go
  dot/config.go
  dot/config/toml/config.go
  dot/network/config.go
  dot/network/connmgr.go
  dot/network/connmgr_test.go
  dot/network/host.go
  dot/services.go
  go.mod
Labels: network, pr-approved

#1514 chore(release): Update name in package.json.
  .github/workflows/release.yml
  .releaserc
  go.sum
  package.json
Labels: pr-approved

#1511 feat(dot/network): Add cache for network message.
  dot/network/host.go
  dot/network/host_test.go
  dot/network/message_cache.go
  dot/network/message_cache_test.go
  dot/network/notifications.go
  dot/network/service_test.go
  dot/network/test_helpers.go
  go.mod
Labels: network, pr-approved

#1516 chore(release): Fix Deepsource error on development branch.
  cmd/gossamer/account.go
  cmd/gossamer/main.go
  cmd/gossamer/utils.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/network/sync.go
  dot/node_test.go
  dot/rpc/helpers.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/system.go
  dot/rpc/subscription/websocket.go
  dot/state/service.go
  dot/state/service_test.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
  dot/types/block_test.go
  dot/types/header.go
  dot/types/header_test.go
  lib/babe/babe_test.go
  lib/babe/build.go
  lib/babe/build_test.go
  lib/babe/median.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/database_test.go
  lib/blocktree/leaves.go
  lib/common/optional/types.go
  lib/genesis/helpers.go
  lib/grandpa/grandpa.go
  lib/keystore/helpers.go
  lib/keystore/keystore.go
  lib/runtime/extrinsic/unchecked_extrinsic.go
  lib/runtime/life/instance.go
  lib/runtime/life/resolver.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmtime/imports.go
  lib/scale/decode.go
  lib/scale/encode.go
  lib/trie/database.go
  lib/trie/encode.go
  lib/trie/node.go
  lib/utils/test_utils.go
  tests/polkadotjs_test/start_polkadotjs_test.go
  tests/utils/chain.go
  tests/utils/header.go
Labels: chore, pr-approved

#1523 chore(codeowners): update codeowners file
  .github/CODEOWNERS
Labels: chore, pr-approved

#1517 fix(dot/network): fix receiving notifications messages
  dot/network/block_announce.go
  dot/network/connmgr.go
  dot/network/connmgr_test.go
  dot/network/message.go
  dot/network/notifications.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/sync.go
  dot/network/sync_test.go
  dot/network/utils.go
  dot/sync/syncer.go
Labels: needs review, network

#1526 chore(.github): remove development from release flow
  .github/workflows/release.yml
Labels: chore, pr-approved

#1519 chore(dot/network, lib/grandpa): update network.ConsensusMessage, add grandpa.NeighbourMessage and handle accordingly
  dot/network/message.go
  dot/network/message_test.go
  dot/network/sync.go
  dot/state/block.go
  dot/state/block_data.go
  dot/state/block_test.go
  dot/sync/syncer.go
  lib/grandpa/grandpa.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/state.go
  lib/grandpa/vote_message.go
Labels: network, pr-approved

#1520 feat: Add properties and chainId on build-spec command
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  cmd/gossamer/main_test.go
  dot/build_spec.go
  dot/build_spec_test.go
Labels: pr-approved

#1529 feat(dot/network, lib/grandpa): request justification on receiving NeighbourMessage, verify justification on receipt
  dot/core/test_helpers.go
  dot/network/host.go
  dot/network/state.go
  dot/network/sync.go
  dot/network/sync_justification.go
  dot/network/sync_justification_test.go
  dot/network/test_helpers.go
  dot/node.go
  dot/rpc/modules/system_test.go
  dot/services.go
  dot/services_test.go
  dot/state/service.go
  dot/sync/interface.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
  lib/grandpa/types.go
  lib/grandpa/types_test.go
  lib/grandpa/vote_message.go
Labels: needs review

#1460 fix (dot/rpc, dot/state): state_subscribeStorage to only notify for value changes
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/messages.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
  dot/rpc/websocket_test.go
  dot/state/storage.go
  dot/state/storage_notify.go
  dot/state/storage_notify_test.go
  go.mod
  tests/polkadotjs_test/package-lock.json
  tests/polkadotjs_test/test_transaction.js
Labels: needs review, rpc

#1536 fix(lib/babe): fix BABE state storing after building block
  go.mod
  lib/babe/babe.go
  tests/polkadotjs_test/test_transaction.js
Labels: babe, pr-approved

#1534 chore(lib/grandpa): update grandpa message types to match substrate
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/network_test.go
  lib/grandpa/round_test.go
  lib/grandpa/types.go
  lib/grandpa/vote_message.go
Labels: grandpa, pr-approved

#1530 fix(babe): Fix extrinsic format in block.
  dot/telemetry/telemetry.go
  lib/babe/build.go
  lib/babe/errors.go
  lib/babe/errors_test.go
  lib/common/optional/types.go
  lib/common/optional/types_test.go
  tests/stress/stress_test.go
Labels: babe, pr-approved

#1542 chore:remove codecov token
  .github/workflows/tests.yml
Labels: pr-approved

#1540 chore(dot/core, dot/state, lib/grandpa): implement GrandpaState, use in DigestHandler and grandpa.Service
  dot/core/digest.go
  dot/core/digest_test.go
  dot/core/errors.go
  dot/core/interface.go
  dot/core/service.go
  dot/core/test_helpers.go
  dot/node.go
  dot/services.go
  dot/services_test.go
  dot/state/grandpa.go
  dot/state/grandpa_test.go
  dot/state/initialize.go
  dot/state/service.go
  dot/types/grandpa.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message_handler.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
  lib/grandpa/types.go
  lib/grandpa/types_test.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
  lib/scale/encode.go
Labels: grandpa, needs review

#1546 chore(dot/state): create BaseState for accessing non-prefixed db keys
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  dot/node.go
  dot/node_test.go
  dot/services.go
  dot/state/base.go
  dot/state/base_test.go
  dot/state/block.go
  dot/state/epoch.go
  dot/state/grandpa.go
  dot/state/initialize.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  lib/scale/encode.go
Labels: needs review, state

#1544 feat(lib/grandpa): fully verify justifications using GrandpaState
  dot/core/digest.go
  dot/core/interface.go
  dot/network/sync.go
  dot/node.go
  dot/state/block_notify.go
  dot/state/grandpa.go
  dot/state/grandpa_test.go
  dot/state/service.go
  dot/state/service_test.go
  dot/sync/interface.go
  dot/sync/syncer.go
  dot/telemetry/telemetry.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/state.go
Labels: grandpa, pr-approved

#1547 chore(lib/common) implement MustHexToBigInt
  dot/import.go
  lib/common/common.go
  lib/common/common_test.go
Labels: chore, pr-approved

#1545 fix(dot/network): Fix notification handshake and reuse stream.
  dot/network/block_announce.go
  dot/network/block_announce_test.go
  dot/network/gossip_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/test_helpers.go
  dot/network/utils.go
  tests/stress/stress_test.go
Labels: needs review, network

#1543 Feat/persist node name
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/main.go
  cmd/gossamer/main_test.go
  cmd/gossamer/utils.go
  dot/node.go
  dot/node_test.go
  dot/state/base.go
  dot/utils.go
  lib/common/db_keys.go
Labels: needs review
