Repository ChainSafe/gossamer, pull requests merged in 2021-08, with the labels that each got.

#1704 feat(dot/rpc) implement `author_hasSessionKeys` RPC call
  dot/core/service.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/service_test.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/messages.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
  go.sum
  lib/crypto/sr25519/sr25519.go
  lib/keystore/helpers.go
  lib/runtime/constants.go
  lib/runtime/interface.go
  lib/runtime/life/exports.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmtime/exports.go
Labels: Status: Approved, rpc

#1672 feat(dot/rpc) add `grandpa_subscribeJustifications` rpc call
  dot/rpc/http.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/messages.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
Labels: Status: Review Needed, rpc

#1710 chore(lib/runtime): stub v0.9.8 runtime funcs, partially implement storage ext_ funcs
  lib/runtime/constants.go
  lib/runtime/test_helpers.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/test_helpers.go
Labels: Status: Review Needed

#1708 fix(lib/grandpa): fix grandpa stall and various bugs
  dot/core/interface.go
  dot/network/mock_block_state.go
  dot/network/service.go
  dot/network/state.go
  dot/network/sync.go
  dot/network/test_helpers.go
  dot/rpc/modules/api.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/mocks/BlockAPI.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/system_test.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/websocket_test.go
  dot/state/block.go
  dot/state/block_finalisation.go
  dot/state/block_finalisation_test.go
  dot/state/grandpa.go
  dot/sync/interface.go
  dot/sync/mocks/FinalityGadget.go
  dot/sync/mocks/finality_gadget.go
  dot/sync/syncer.go
  dot/sync/test_helpers.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/message_tracker.go
  lib/grandpa/network_test.go
  lib/grandpa/state.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
Labels: Status: Review Needed

#1715 feat(dot/rpc) implement `author_hasSessionKeys` RPC call
  dot/core/mocks/block_producer.go
  dot/core/mocks/block_state.go
  dot/core/mocks/digest_handler.go
  dot/core/mocks/network.go
  dot/core/service.go
  dot/core/service_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/service_test.go
  go.sum
  lib/crypto/sr25519/sr25519.go
  lib/crypto/sr25519/sr25519_test.go
  lib/keystore/helpers.go
  lib/keystore/helpers_test.go
  lib/runtime/constants.go
  lib/runtime/interface.go
  lib/runtime/life/exports.go
  lib/runtime/mocks/instance.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmtime/exports.go
Labels: Status: Approved

#1707 feat(dot/rpc/modules) implement `state_queryStorage` rpc method
  .github/workflows/tests.yml
  dot/core/interface.go
  dot/core/service.go
  dot/core/service_test.go
  dot/network/service.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  tests/rpc/rpc_05-state_test.go
Labels: rpc, Status: Approved

#1712 feat(dot/rpc/modules): add `system_addReservedPeer` and `system_removeReservedPeer` RPC call
  dot/network/host.go
  dot/network/host_test.go
  dot/network/service.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/network_api.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  dot/rpc/service_test.go
  dot/rpc/subscription/websocket_test.go
Labels: Status: Changes Requested, Status: Approved

#1724 chore: updated pr template to include primary reviewer
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Chore, Status: Review Needed

#1686 fix(rpc/subscription): subscribe runtime version notify when version changes
  dot/core/service_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/api_mocks_test.go
  dot/rpc/modules/mocks/BlockAPI.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/websocket_test.go
  dot/state/block.go
  dot/state/block_notify.go
  dot/state/block_notify_test.go
  go.mod
  lib/runtime/mocks/version.go
Labels: Status: Approved

#1728 fix(dot/network): Avoid printing extrinsic in TransactionMessage.
  dot/network/transaction.go
Labels: Type: Chore, Status: Review Needed

#1730 chore: isolated test workflows for individual job runs
  .github/workflows/code-cov.yml
  .github/workflows/docker-grandpa.yml
  .github/workflows/docker-js.yml
  .github/workflows/docker-rpc.yml
  .github/workflows/docker-stable.yml
  .github/workflows/docker-stress.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
Labels: Status: Review Needed, ci

#1723 feat(dot/rpc) Protect unsafe RPC methods
  cmd/gossamer/config.go
  cmd/gossamer/flags.go
  dot/config.go
  dot/config/toml/config.go
  dot/node.go
  dot/rpc/helpers.go
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/modules/rpc.go
  dot/rpc/service.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
  dot/rpc/websocket_test.go
  dot/services.go
  tests/utils/gossamer_utils.go
Labels: rpc, Status: Approved

#1733 Return on EOF error while reading stream.
  dot/network/host_test.go
  dot/network/service.go
  dot/network/test_helpers.go
Labels: Status: Review Needed

#1735 feat(dot/rpc) implement RPC aliases
  dot/rpc/dot_up_codec.go
  dot/rpc/dot_up_codec_test.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/rpc.go
Labels: rpc, Status: Review Needed

#1734 feat(lib/trie) implement merkle proofs for tries
  lib/trie/proof.go
  lib/trie/proof_test.go
  lib/trie/trie.go
Labels: Status: Approved

#1740 feat(dot/rpc) implement `chain_subscribeAllHeads` RPC
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
Labels: Status: Changes Requested, rpc, Status: Review Needed

#1731 chore: fix deepsource issues found in release v0.6.0
  dot/network/connmgr.go
  dot/network/host.go
  dot/rpc/service.go
  dot/state/test_helpers.go
  lib/scale/encode.go
  lib/trie/test_utils.go
Labels: Status: Approved

#1769 chore(lib/grandpa): update grandpa message tracker to store messages with map of maps, also store commit messages
  dot/network/sync.go
  dot/network/sync_test.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_tracker.go
  lib/grandpa/message_tracker_test.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
Labels: Status: Approved

#1751 Staging integration workflow for syncing Polkadot + Kusama nodes
  .github/workflows/staging.yml
  .github/workflows/staging/kusama-taskdef.json
  .github/workflows/staging/openmetrics.d/kusama-conf.yaml
  .github/workflows/staging/openmetrics.d/polkadot-conf.yaml
  .github/workflows/staging/polkadot-taskdef.json
  Dockerfile.staging
Labels: Status: Approved
