Repository ChainSafe/gossamer, pull requests merged in 2021-12, with the labels that each got.

#1995 testing (rpc/modules): write new unit tests to increase code coverage
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_integration_test.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/childstate.go
  dot/rpc/modules/childstate_test.go
  dot/rpc/modules/dev_integration_test.go
  dot/rpc/modules/dev_test.go
  dot/rpc/modules/grandpa.go
  dot/rpc/modules/grandpa_test.go
  dot/rpc/modules/mocks/block_producer_api.go
  dot/rpc/modules/mocks/sync_state_api.go
  dot/rpc/modules/offchain_test.go
  dot/rpc/modules/payment_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_integration_test.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/sync_state.go
  dot/rpc/modules/sync_state_test.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_integration_test.go
  dot/rpc/modules/system_test.go
  dot/rpc/modules/test_data/test_metadata.go
  dot/rpc/modules/test_data/test_metadata.zip
Labels: tests

#1957 testing (rpc/modules): migrate current tests to integration tests, write new unit tests
  .golangci.yml
  dot/rpc/modules/api.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/chain.go
  dot/rpc/modules/chain_integration_test.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/childstate.go
  dot/rpc/modules/childstate_integration_test.go
  dot/rpc/modules/childstate_test.go
  dot/rpc/modules/dev_integration_test.go
  dot/rpc/modules/dev_test.go
  dot/rpc/modules/grandpa.go
  dot/rpc/modules/grandpa_integration_test.go
  dot/rpc/modules/grandpa_test.go
  dot/rpc/modules/mocks/block_producer_api.go
  dot/rpc/modules/mocks/sync_state_api.go
  dot/rpc/modules/offchain_integration_test.go
  dot/rpc/modules/offchain_test.go
  dot/rpc/modules/payment_integration_test.go
  dot/rpc/modules/payment_test.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_integration_test.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/sync_state.go
  dot/rpc/modules/sync_state_integration_test.go
  dot/rpc/modules/sync_state_test.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_integration_test.go
  dot/rpc/modules/system_test.go
  dot/rpc/modules/test_data/test_metadata.go
  dot/rpc/modules/test_data/test_metadata.zip
Labels: tests

#2110 chore(runtime): remove runtime imports prefix logs
  lib/runtime/life/resolver.go
  lib/runtime/wasmer/imports.go
Labels: runtime, Status: Review Needed

#2100 docs(network): README
  dot/network/README.md
Labels: Type: Documentation

#2077 chore(lib/trie): refactor encoding and hash related code in trie package
  internal/trie/codec/nibbles.go
  internal/trie/codec/nibbles_test.go
  internal/trie/node/branch.go
  internal/trie/node/branch_encode.go
  internal/trie/node/branch_encode_test.go
  internal/trie/node/branch_test.go
  internal/trie/node/buffer.go
  internal/trie/node/buffer_mock_test.go
  internal/trie/node/children.go
  internal/trie/node/children_test.go
  internal/trie/node/copy.go
  internal/trie/node/copy_test.go
  internal/trie/node/decode.go
  internal/trie/node/decode_test.go
  internal/trie/node/dirty.go
  internal/trie/node/dirty_test.go
  internal/trie/node/encode_decode_test.go
  internal/trie/node/encode_doc.go
  internal/trie/node/encode_test.go
  internal/trie/node/generation.go
  internal/trie/node/generation_test.go
  internal/trie/node/hash.go
  internal/trie/node/hash_test.go
  internal/trie/node/header.go
  internal/trie/node/header_test.go
  internal/trie/node/key.go
  internal/trie/node/key_test.go
  internal/trie/node/leaf.go
  internal/trie/node/leaf_encode.go
  internal/trie/node/leaf_encode_test.go
  internal/trie/node/leaf_test.go
  internal/trie/node/node.go
  internal/trie/node/reader_mock_test.go
  internal/trie/node/types.go
  internal/trie/node/value.go
  internal/trie/node/value_test.go
  internal/trie/node/writer_mock_test.go
  internal/trie/pools/pools.go
  internal/trie/record/node.go
  internal/trie/record/recorder.go
  internal/trie/record/recorder_test.go
  lib/trie/bytesBuffer_mock_test.go
  lib/trie/codec.go
  lib/trie/codec_test.go
  lib/trie/database.go
  lib/trie/hash.go
  lib/trie/hash_test.go
  lib/trie/lookup.go
  lib/trie/node.go
  lib/trie/node_mock_test.go
  lib/trie/node_test.go
  lib/trie/print.go
  lib/trie/proof.go
  lib/trie/proof_test.go
  lib/trie/readwriter_mock_test.go
  lib/trie/recorder.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: trie
