Repository ChainSafe/gossamer, pull requests merged in 2021-05, with the labels that each got.

#1553 fix(dot/network): split stored streams and handshakeData into inbound and outbound
  dot/network/block_announce.go
  dot/network/block_announce_test.go
  dot/network/host_test.go
  dot/network/light_test.go
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/sync.go
  dot/network/sync_test.go
  dot/network/test_helpers.go
Labels: pr-approved

#1552 chore(docs): fix image paths for integrate docs page
  docs/docs/integrate/connect-to-polkadot-js.md
Labels: chore, pr-approved

#1557 fix(build): go-schnorrkel version
  go.mod
  go.sum
Labels: pr-approved

#1551 fix(dot): Closes db if node initialized check fails
  dot/node.go
Labels: pr-approved

#1555 feat(dot/network): add propagate return bool to messageHandler func type to determine whether to propagate message or not
  dot/network/block_announce.go
  dot/network/block_announce_test.go
  dot/network/notifications.go
  dot/network/transaction.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
Labels: needs review, network

#1528 feat (dot/telemetry): implement telemetry system.interval message
  dot/network/config.go
  dot/network/host.go
  dot/network/service.go
  dot/telemetry/telemetry.go
  dot/telemetry/telemetry_test.go
Labels: pr-approved, tooling

#1558 feat(lib/grandpa): send NeighbourMessage to peers
  dot/core/digest.go
  dot/core/interface.go
  dot/rpc/modules/api.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
  dot/rpc/websocket_test.go
  dot/state/block.go
  dot/state/block_notify.go
  dot/state/block_notify_test.go
  dot/types/grandpa.go
  lib/grandpa/grandpa.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
  lib/grandpa/state.go
Labels: grandpa, pr-approved

#1559 chore: merge main into development before release
  go.sum
Labels: pr-approved

#1566 fix(release): Trigger release when pushed to main branch.
  package.json
Labels: chore, needs review

#1572 fix(dot/sync): fix creating block response, fixes node sync between gossamer nodes
  dot/network/notifications.go
  dot/network/sync.go
  dot/state/storage_notify_test.go
  dot/sync/interface.go
  dot/sync/message.go
  dot/sync/message_test.go
  lib/grandpa/network.go
Labels: needs review

#1581 fix(lib/babe): add pre-runtime digest before calling initialize_block
  dot/types/digest.go
  lib/babe/build.go
  lib/babe/build_test.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmer/exports_test.go
Labels: babe, pr-approved

#1567 chore: add polkadotjs tests to ci
  .github/workflows/tests.yml
  Dockerfile
  tests/polkadotjs_test/package.json
  tests/polkadotjs_test/start_polkadotjs_test.go
  tests/polkadotjs_test/test/test-polkadot.js
  tests/polkadotjs_test/yarn.lock
  tests/utils/gossamer_utils.go
Labels: ci, pr-approved

#1585 fix(lib/babe): call AddBlock in BABE synchronously after block is built
  dot/core/service.go
  lib/babe/babe.go
Labels: babe, pr-approved

#1583 chore(docs): update README and installation doc to include dev node
  README.md
  docs/docs/getting-started/installation.md
Labels: docs, pr-approved

#1582 fix(docs) rename hosts package to dot packages
  docs/docs/getting-started/overview/package-library.md
Labels: docs, pr-approved

#1590 chore(workflow): improved ci caching for mod and build
  .github/workflows/build.yml
  .github/workflows/checks.yml
  .github/workflows/tests.yml
Labels: chore, pr-approved

#1593 chore: fix block production path and add article links
  docs/docs/contributing.md
  docs/docs/getting-started/overview/host-architecture.md
  docs/docs/getting-started/resources/general-resources.md
  docs/docs/usage/command-line.md
Labels: docs, pr-approved

#1574 feat(rpc/subscription): implement state_unsubscribeStorage
  dot/rpc/subscription/messages.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
Labels: pr-approved, rpc

#1592 fix: pending bubble hidden after block included
  dot/rpc/subscription/listeners.go
  dot/types/body.go
  dot/types/body_test.go
  lib/babe/build_test.go
Labels: pr-approved

#1575 fix(dot/network) track sent/received requests by hash
  dot/network/sync.go
  dot/network/sync_test.go
Labels: network, pr-approved

#1594 fix(dot/network): fix discovery between gossamer nodes
  dot/network/discovery.go
  dot/network/discovery_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/mdns.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/sync.go
  dot/state/block.go
  go.mod
  go.sum
Labels: needs review, network

#1598 fix(utils): create a specific folder for database
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  dot/node.go
  dot/services.go
  dot/state/base.go
  dot/state/initialize.go
  dot/state/service.go
  dot/state/test_helpers.go
  lib/blocktree/database_test.go
  lib/grandpa/grandpa_test.go
  lib/trie/database_test.go
  lib/utils/utils.go
Labels: pr-approved

#1601 chore(review): Add Eclesio to code owner.
  .github/CODEOWNERS
Labels: pr-approved

#1600 chore(dot/network): use sync.Pool for network message buffers
  dot/network/config.go
  dot/network/notifications.go
  dot/network/pool.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/sync.go
Labels: needs changes, needs review

#1603 fix(cmd): update deprecated package
  cmd/gossamer/utils.go
  go.mod
Labels: pr-approved

#1605 fix(lib/blocktree): fix setting leaves after blocktree pruning
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
Labels: pr-approved

#1597 fix (dot/telemetry): refactor telemetry to reduce CPU usage
  dot/network/service.go
  dot/node.go
  dot/sync/syncer.go
  dot/telemetry/telemetry.go
  dot/telemetry/telemetry_test.go
Labels: needs review, pr-approved, tooling

#1608 chore(dot/network): improve CPU usage again; no more mallocs
  dot/network/discovery.go
  dot/network/service.go
  dot/network/utils.go
  go.mod
Labels: needs review
