Repository ChainSafe/gossamer, pull requests merged in 2021-07, with the labels that each got.

#1656 feat(lib/transactions) ready transactions metrics
  dot/metrics/collector.go
  dot/metrics/metrics.go
  dot/node.go
  dot/state/service.go
  dot/state/service_test.go
  lib/transaction/pool.go
  lib/transaction/priority_queue.go
Labels: Status: Approved, metrics

#1657 feat(lib/trie): Parallel hash trie.
  dot/state/service_test.go
  go.mod
  go.sum
  lib/trie/encode.go
  lib/trie/hash.go
  lib/trie/hash_test.go
  lib/trie/node.go
  lib/trie/node_test.go
  lib/trie/print.go
  lib/trie/test_utils.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed, trie

#1666 refactor(dot/rpc/modules) Add author unit tests, migrate old tests to integration tests
  dot/rpc/modules/author.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/mocks/TransactionStateAPI.go
  dot/rpc/modules/mocks/block_api.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/modules/mocks/storage_api.go
  dot/rpc/modules/system_test.go
Labels: Status: Approved

#1670 chore (pkg/scale) scale babe integration
  dot/sync/test_helpers.go
  lib/babe/build.go
  lib/babe/build_test.go
  lib/babe/errors.go
  lib/babe/errors_test.go
  lib/transaction/types.go
  lib/transaction/types_test.go
  pkg/scale/decode.go
Labels: Status: Review Needed, Type: Chore, scale

#1655 feat(lib/grandpa) implement grandpa finality round metrics
  dot/metrics/collector.go
  dot/node.go
  go.mod
  go.sum
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
Labels: Status: Review Needed, metrics

#1662 fix(dot/network, lib/grandpa): fix node sync, improve devnet finality
  dot/digest/digest_test.go
  dot/network/notifications.go
  dot/network/sync.go
  dot/network/sync_test.go
  dot/state/block.go
  dot/state/block_notify_test.go
  dot/sync/message.go
  dot/sync/message_test.go
  go.sum
  lib/common/hash.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/message_tracker_test.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
  lib/grandpa/types.go
  lib/grandpa/types_test.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
Labels: Status: Review Needed

#1671 fix(dot/node) Start websocket server only with `--ws` flag
  dot/node.go
Labels: Status: Review Needed, rpc

#1660 fix (dot/telemetry): NoTelemetry flag stops telemetry
  dot/node.go
  dot/telemetry/telemetry.go
  dot/telemetry/telemetry_test.go
Labels: Status: Review Needed, tooling

#1673 proposal(dot/rpc/subscription): refactoring the websocket `HandleComm`
  dot/rpc/http.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/subscription.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
Labels: Status: Review Needed, rpc

#1669 chore (pkg/scale) scale integration into genesis
  dot/rpc/modules/system_test.go
  dot/types/account.go
  lib/genesis/helpers.go
  lib/runtime/wasmer/exports_test.go
  pkg/scale/comparison_test.go
  pkg/scale/encode.go
  pkg/scale/encode_test.go
Labels: Status: Review Needed, Type: Chore, scale

#1683 fix(dot/network): fix stream manager tests
  dot/network/stream_manager_test.go
Labels: Status: Approved

#1676 chore (pkg/scale) integrate scale into dot/core and dot/sync
  dot/core/messages_test.go
  dot/core/service.go
Labels: Status: Approved, Type: Chore, scale

#1678 chore (pkg/scale) integrate scale pkg into dot/rpc
  dot/rpc/modules/state.go
  dot/rpc/modules/system.go
Labels: Status: Approved, Type: Chore, scale

#1664 feat(lib/grandpa) add round state rpc call
  Makefile
  dot/node.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/grandpa.go
  dot/rpc/modules/grandpa_test.go
  dot/rpc/modules/mocks/block_finality_api.go
  dot/services.go
  dot/services_test.go
  lib/grandpa/grandpa.go
  lib/grandpa/mocks/network.go
Labels: Status: Approved, rpc

#1668 chore: replace unbuffered channels with buffered channels
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/websocket.go
Labels: Status: Changes Requested, Status: Review Needed, Type: Chore

#1679 lib/babe: always use 2/3 of slot to produce block, re-add potentially valid txs to queue
  lib/babe/build.go
  lib/babe/errors.go
  lib/babe/errors_test.go
Labels: Status: Review Needed, babe

#1687 fix(lib/grandpa): Fix max value for digest.
  dot/digest/digest.go
  go.sum
  lib/grandpa/grandpa.go
Labels: Status: Approved

#1690 feat(dot/rpc) Add `system_localPeerId` rpc call
  dot/rpc/modules/mocks/network_api.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  dot/rpc/service_test.go
Labels: Status: Review Needed, rpc

#1692 chore: added cname for docs
  docs/docs/CNAME
Labels: Status: Approved

#1689 feat(dot/rpc) Add `system_localListenAddresses` RPC call
  dot/rpc/modules/mocks/system_api.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  dot/rpc/service_test.go
  go.sum
Labels: Status: Approved, rpc

#1691 feat(dot/rpc) Add `system_syncState` rpc call
  dot/network/service.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/network_api.go
  dot/rpc/modules/system.go
  dot/rpc/modules/system_test.go
  dot/rpc/service_test.go
Labels: Status: Approved, rpc

#1693 chore(lib/common) implement byte pool to improve websocket subscription efficiency
  dot/core/interface.go
  dot/digest/digest.go
  dot/digest/interface.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/block_api.go
  dot/state/block.go
  dot/state/block_notify.go
  dot/state/block_notify_test.go
  lib/common/bytepool.go
  lib/common/bytepool_test.go
  lib/grandpa/grandpa.go
  lib/grandpa/state.go
Labels: Status: Approved

#1697 feat(dot/network) add `network_is_major_syncing` metric
  chain/polkadot/config.toml
  dot/config.go
  dot/network/block_announce.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/sync.go
  dot/node.go
  lib/grandpa/grandpa_test.go
Labels: Status: Approved

#1703 fix(dot/network): decrease DHT find peers interval for gssmr nodes
  chain/gssmr/config.toml
  chain/gssmr/defaults.go
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  cmd/gossamer/export_test.go
  dot/config.go
  dot/config/toml/config.go
  dot/network/config.go
  dot/network/service.go
  dot/services.go
Labels: Status: Review Needed

#1705 fix(dot/state): fix runtime panic due to stopped runtime
  dot/core/service.go
  dot/state/block.go
  lib/blocktree/blocktree.go
  lib/runtime/wasmer/instance.go
Labels: Status: Approved, Status: Review Needed

#1706 fix(docs): improve build-spec usage docs
  docs/docs/usage/import-runtime.md
Labels: Status: Review Needed

#1700 fix(dot/state): add StorageState Lock/Unlock API for usage by babe and sync
  dot/core/service.go
  dot/core/service_test.go
  dot/network/sync.go
  dot/state/block.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  dot/state/storage_test.go
  dot/sync/interface.go
  dot/sync/syncer.go
  lib/babe/babe.go
  lib/babe/state.go
  lib/blocktree/blocktree.go
  lib/runtime/wasmer/instance.go
  lib/trie/node.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Approved

#1711 maintainence: add Jimmy to codeowners
  .github/CODEOWNERS
Labels: Status: Review Needed
