Repository ChainSafe/gossamer, pull requests merged in 2021-09, with the labels that each got.

#1713 feat(lib/runtime) implement perlin/life imports to v0.9
  lib/runtime/life/instance.go
  lib/runtime/life/resolver.go
  lib/runtime/life/resolver_test.go
  lib/runtime/life/test_helpers.go
Labels: Status: Approved

#1774 feat(dot/rpc) implement `offchain_localStorageSet` and `offchain_localStorageGet`
  cmd/gossamer/config.go
  cmd/gossamer/main.go
  dot/node.go
  dot/node_test.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/runtime_storage_api.go
  dot/rpc/modules/offchain.go
  dot/rpc/modules/offchain_test.go
  dot/services.go
  dot/services_test.go
  lib/runtime/types.go
  lib/trie/proof_test.go
Labels: rpc, Status: Review Needed

#1783 fix: fix Kusama sync; add storageState lock in core.HandleTransactionMessage
  dot/core/interface.go
  dot/core/messages.go
  dot/rpc/modules/author_integration_test.go
Labels: Status: Review Needed

#1789 Fix deepsource errors.
  dot/network/block_announce.go
  dot/network/gossip_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/service.go
  dot/network/service_test.go
  lib/grandpa/network.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
Labels: Status: Approved

#1780 fix(dot/core): Batch process transaction message.
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/service.go
  dot/network/transaction.go
  dot/sync/interface.go
  lib/babe/state.go
  lib/grandpa/network.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
Labels: Status: Approved

#1786 chore(CI): Check PR body and title.
  .github/PULL_REQUEST/pull_request.go
  .github/workflows/checks.yml
  lib/utils/pull_request.go
  lib/utils/pull_request_test.go
Labels: Status: Review Needed

#1801 fix(lib/babe): fix error log
  lib/babe/verify.go
Labels: Status: Review Needed

#1736 fix: confirm block import notifier is closed properly
  .deepsource.toml
  dot/core/interface.go
  dot/core/mocks/block_state.go
  dot/digest/digest.go
  dot/digest/interface.go
  dot/rpc/http.go
  dot/rpc/modules/api.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/mocks/block_api.go
  dot/rpc/modules/system_test.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_test.go
  dot/state/block.go
  dot/state/block_notify.go
  dot/state/block_notify_test.go
  lib/grandpa/grandpa.go
  lib/grandpa/message_tracker.go
  lib/grandpa/message_tracker_test.go
  lib/grandpa/state.go
  lib/grandpa/vote_message_test.go
Labels: Status: Changes Requested, Status: Review Needed

#1739 feat: implement ext_offchain_index_set_version_1 for wasmer runtime
  dot/core/test_helpers.go
  dot/services.go
  dot/state/base.go
  dot/sync/test_helpers.go
  lib/babe/babe_test.go
  lib/runtime/types.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
  lib/runtime/wasmer/test_helpers.go
Labels: Status: Changes Requested, runtime, Status: Review Needed

#1800 feat(dot/rpc): Implement `childstate_getKeys` rpc call
  chain/dev/config.toml
  chain/dev/defaults.go
  chain/gssmr/config.toml
  chain/gssmr/defaults.go
  chain/kusama/config.toml
  chain/kusama/defaults.go
  chain/polkadot/config.toml
  chain/polkadot/defaults.go
  dot/rpc/http.go
  dot/rpc/http_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/childstate.go
  dot/rpc/modules/childstate_test.go
  dot/rpc/modules/mocks/rpcapi.go
  dot/rpc/modules/mocks/storage_api.go
Labels: rpc, Status: Approved

#1811 chore(lib/grandpa): integrate scale into grandpa
  dot/rpc/modules/grandpa_test.go
  dot/rpc/modules/mocks/block_finality_api.go
  dot/rpc/subscription/listeners_test.go
  dot/rpc/subscription/websocket_test.go
  dot/state/grandpa.go
  dot/state/grandpa_test.go
  dot/types/grandpa.go
  dot/types/grandpa_test.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/message.go
  lib/grandpa/message_handler.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/message_tracker_test.go
  lib/grandpa/network.go
  lib/grandpa/network_test.go
  lib/grandpa/round_test.go
  lib/grandpa/state.go
  lib/grandpa/types.go
  lib/grandpa/types_test.go
  lib/grandpa/vote_message.go
  lib/grandpa/vote_message_test.go
Labels: Type: Chore, Status: Review Needed

#1768 feat(rpc): Implement `state_getReadProof` rpc call
  dot/core/interface.go
  dot/core/mocks/block_state.go
  dot/core/mocks/storage_state.go
  dot/core/service.go
  dot/core/service_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/subscription/websocket_test.go
  dot/state/block.go
  dot/state/storage.go
  go.mod
  go.sum
  lib/babe/build_test.go
  lib/trie/lookup.go
  lib/trie/proof.go
  lib/trie/proof_test.go
  lib/trie/recorder.go
  lib/trie/test_utils.go
Labels: Status: Changes Requested, rpc, Status: Review Needed
