Repository ChainSafe/gossamer, pull requests merged in 2021-06, with the labels that each got.

#1607 fix(dot/core): Fix handle transaction message test.
  .github/workflows/build.yml
  .github/workflows/tests.yml
  dot/core/messages.go
  dot/core/messages_test.go
  go.sum
  lib/grandpa/round_test.go
Labels: pr-approved

#1611 feat(dot/network): implement streamManager to cleanup not recently used streams
  dot/network/service.go
  dot/network/stream_manager.go
  dot/network/stream_manager_test.go
  dot/network/utils.go
Labels: Status: Review Needed

#1615 fix(dot/network): implement a handshake timeout
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/utils.go
Labels: Status: Approved, network

#1617 fix(dot/network): check if peer supports protocol
  dot/network/host.go
  dot/network/host_test.go
  dot/network/notifications.go
Labels: Status: Approved

#1609 fix(dot/core): Add only extrinsic during chain reorg.
  dot/core/messages.go
  dot/core/service.go
  dot/core/service_test.go
  dot/sync/message_test.go
  dot/sync/syncer_test.go
  dot/sync/test_helpers.go
  dot/types/extrinsic.go
  lib/babe/build.go
  lib/babe/build_test.go
Labels: Status: Approved

#1627 maintainence: attempt to fix network tests on CI
  dot/core/test_helpers.go
  dot/network/block_announce_test.go
  dot/network/config.go
  dot/network/connmgr.go
  dot/network/connmgr_test.go
  dot/network/discovery_test.go
  dot/network/gossip_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/light_test.go
  dot/network/mdns_test.go
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/service_test.go
  dot/network/sync_justification_test.go
  dot/network/sync_test.go
  dot/network/transaction_test.go
  dot/rpc/modules/system_test.go
Labels: Status: Review Needed

#1613 fix(dot/state, lib/babe, lib/trie): improve syncing between gossamer authority nodes
  dot/network/service_test.go
  dot/rpc/modules/dev_test.go
  dot/state/block.go
  dot/state/storage.go
  dot/state/storage_test.go
  dot/utils_test.go
  lib/babe/babe.go
  lib/babe/build.go
  lib/runtime/storage/trie.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Approved

#1631 fix(dot/network, lib/grandpa): fix handshake decoding and grandpa message handler sigabort
  Makefile
  dot/network/notifications.go
  dot/network/service.go
  dot/state/block.go
  lib/babe/babe.go
  lib/grandpa/grandpa.go
  lib/grandpa/message_handler.go
  lib/grandpa/network.go
  lib/grandpa/vote_message.go
Labels: Status: Review Needed

#1632 chore: remove finalnum inherent, clear babe `slotToProof` map
  dot/sync/test_helpers.go
  dot/types/babe.go
  dot/types/inherents.go
  lib/babe/build.go
  lib/babe/epoch.go
  lib/runtime/life/exports_test.go
  lib/runtime/wasmer/exports_test.go
Labels: Status: Review Needed

#1634 fix(dot/network): Check for size when decoding leb128.
  dot/network/utils.go
  dot/network/utils_test.go
Labels: Status: Review Needed

#1626 fix(dot,lib): Replacing handmade mocks to generated new ones
  .github/CONTRIBUTING.md
  Makefile
  dot/core/digest.go
  dot/core/digest_test.go
  dot/core/messages_test.go
  dot/core/mocks/block_producer.go
  dot/core/mocks/network.go
  dot/core/mocks/verifier.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/network/discovery_test.go
  dot/network/mock_block_state.go
  dot/network/mock_syncer.go
  dot/network/mock_transaction_handler.go
  dot/network/service_test.go
  dot/network/state_test.go
  dot/network/sync_test.go
  dot/network/test_helpers.go
  dot/network/transaction_test.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/mocks/block_api.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/modules/mocks/storage_api.go
  dot/rpc/modules/system_test.go
  dot/rpc/subscription/websocket_test.go
  dot/rpc/websocket_test.go
  dot/services_test.go
  dot/state/mock_observer.go
  dot/state/service.go
  dot/state/storage_notify_test.go
  dot/sync/mocks/block_producer.go
  dot/sync/mocks/finality_gadget.go
  dot/sync/mocks/verifier.go
  dot/sync/syncer.go
  dot/sync/test_helpers.go
  dot/types/mocks/digest_item.go
  go.sum
  lib/grandpa/grandpa_test.go
  lib/grandpa/mocks/digest_handler.go
  lib/grandpa/round_test.go
  lib/grandpa/vote_message_test.go
  lib/runtime/allocator_test.go
  lib/runtime/mock_memory.go
  lib/runtime/mock_transaction_state.go
  lib/runtime/wasmer/test_helpers.go
  lib/services/mocks/service.go
  lib/services/services_test.go
  lib/utils/test_utils.go
Labels: Status: Review Needed

#1633 Get node cache
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
Labels: Status: Review Needed

#1636 fix(lib/babe): fix timing for transition between epochs
  go.mod
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/build.go
  lib/babe/epoch.go
  lib/babe/epoch_test.go
  lib/babe/types.go
  lib/common/uint128.go
  lib/keystore/mock_keyring.go
  lib/keystore/mock_keystore.go
Labels: Status: Review Needed

#1596 feat(dot/state): Implement online pruning of state tries.
  chain/dev/defaults.go
  chain/gssmr/defaults.go
  chain/kusama/defaults.go
  chain/polkadot/defaults.go
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export.go
  cmd/gossamer/export_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/flags_test.go
  cmd/gossamer/main.go
  cmd/gossamer/prune_test.go
  cmd/gossamer/utils.go
  cmd/gossamer/utils_test.go
  dot/build_spec.go
  dot/config.go
  dot/config/toml/config.go
  dot/core/digest_test.go
  dot/core/test_helpers.go
  dot/import.go
  dot/node.go
  dot/node_test.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/state_test.go
  dot/rpc/modules/system_test.go
  dot/services.go
  dot/state/base.go
  dot/state/initialize.go
  dot/state/offline_pruner.go
  dot/state/pruner/pruner.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  dot/state/storage_notify_test.go
  dot/state/storage_test.go
  dot/state/test_helpers.go
  dot/sync/interface.go
  dot/sync/syncer.go
  dot/sync/test_helpers.go
  go.mod
  go.sum
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/state.go
  lib/babe/verify_test.go
  lib/common/db_keys.go
  lib/runtime/storage/trie.go
  lib/trie/database.go
  lib/trie/node.go
  lib/trie/trie.go
  lib/trie/trie_test.go
  tests/utils/gossamer_utils.go
Labels: Status: Approved, state

#1647 chore: updated doc links
  .github/workflows/checks.yml
  .github/workflows/tests.yml
  .golangci.yml
  Makefile
  docs/docs/getting-started/overview/host-architecture.md
  docs/docs/integrate/connect-to-polkadot-js.md
  lib/grandpa/message.go
  lib/grandpa/types.go
  lib/runtime/extrinsic/unchecked_extrinsic_test.go
  lib/scale/decode_ptr_test.go
  lib/trie/node.go
  scripts/install-lint.sh
  tests/utils/gossamer_utils.go
Labels: Status: Approved, Type: Documentation

#1645 chore(dot/core, dot/sync, lib/babe): refactor handling on block import to reduce duplicate code
  dot/core/errors.go
  dot/core/interface.go
  dot/core/messages.go
  dot/core/messages_test.go
  dot/core/mocks/digest_handler.go
  dot/core/service.go
  dot/core/service_test.go
  dot/core/test_helpers.go
  dot/digest/digest.go
  dot/digest/digest_test.go
  dot/digest/interface.go
  dot/node.go
  dot/node_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/dev_test.go
  dot/rpc/subscription/websocket.go
  dot/services.go
  dot/services_test.go
  dot/state/block.go
  dot/state/block_test.go
  dot/sync/errors.go
  dot/sync/interface.go
  dot/sync/mocks/block_import_handler.go
  dot/sync/mocks/block_producer.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
  dot/sync/test_helpers.go
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/errors.go
  lib/babe/mocks/BlockImportHandler.go
  lib/babe/state.go
  lib/babe/verify.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
Labels: Status: Review Needed, Urgency: u1

#1644 chore: change tests log level to info
  .github/CONTRIBUTING.md
  Makefile
  dot/sync/test_helpers.go
  lib/babe/build_test.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/test_helpers.go
  lib/runtime/wasmtime/test_helpers.go
  tests/polkadotjs_test/start_polkadotjs_test.go
Labels: Status: Approved, Type: Chore

#1643 fix(dot/core): check transaction Validity.Propagate field to determine whether to propagate tx
  dot/core/messages.go
  dot/core/messages_test.go
  dot/network/mock_transaction_handler.go
  dot/network/state.go
  dot/network/transaction.go
  dot/network/transaction_test.go
  go.sum
Labels: Status: Changes Requested

#1548 refactor(lib/scale): refactor lib/scale into own package with idiomatic types, marshalling, and optionality
  go.mod
  go.sum
  pkg/scale/README.md
  pkg/scale/comparison_test.go
  pkg/scale/decode.go
  pkg/scale/decode_test.go
  pkg/scale/encode.go
  pkg/scale/encode_test.go
  pkg/scale/result.go
  pkg/scale/result_example_test.go
  pkg/scale/result_test.go
  pkg/scale/scale.go
  pkg/scale/scale_test.go
  pkg/scale/uint128.go
  pkg/scale/uint128_test.go
  pkg/scale/varying_data_type.go
  pkg/scale/varying_data_type_example_test.go
  pkg/scale/varying_data_type_test.go
Labels: Status: Approved, scale

#1648 feat(dot/babe) implement block production time metric
  docker-compose.yml
  docs/docs/integrate/using-prometheus.md
  dot/metrics/metrics.go
  dot/network/discovery.go
  dot/network/discovery_test.go
  dot/network/service.go
  dot/node.go
  go.mod
  go.sum
  lib/babe/babe.go
  lib/babe/build.go
  lib/babe/build_test.go
  prometheus.yml
Labels: Status: Approved

#1640 fix(lib/babe): fix setting first slot of network, fix loading BABE epoch params
  dot/core/mocks/verifier.go
  dot/digest/digest_test.go
  dot/network/sync.go
  dot/node.go
  dot/node_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/chain_test.go
  dot/state/base.go
  dot/state/base_test.go
  dot/state/block.go
  dot/state/block_test.go
  dot/state/epoch.go
  dot/state/epoch_test.go
  dot/state/service.go
  dot/state/service_test.go
  dot/sync/syncer_test.go
  dot/types/babe.go
  go.mod
  lib/babe/babe.go
  lib/babe/babe_test.go
  lib/babe/epoch.go
  lib/babe/epoch_test.go
  lib/babe/errors.go
  lib/babe/state.go
  lib/babe/verify.go
  lib/grandpa/message_handler_test.go
  lib/grandpa/message_test.go
  lib/grandpa/network_test.go
  tests/rpc/rpc_01-system_test.go
Labels: Status: Approved, babe

#1650 chore: replace time.After with time.NewTicker
  dot/network/discovery.go
  dot/network/sync.go
  dot/telemetry/telemetry.go
  lib/grandpa/network.go
Labels: Status: Approved, Type: Chore
