Repository ChainSafe/gossamer, pull requests merged in 2021-11, with the labels that each got.

#1959 fix(dot/state): fix deadlock, fixes bootstrap syncing
  dot/core/service.go
  dot/state/block.go
  dot/state/block_finalisation.go
  dot/sync/chain_processor.go
  lib/runtime/test_helpers.go
  scripts/install-lint.sh
Labels: Status: Review Needed

#1982 fix(lib/grandpa): use `defaultGrandpaInterval` if not set, fixes error on startup
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
Labels: Status: Review Needed

#1960 chore(pr-check-fix): Fix PR check (again)
  lib/utils/pull_request.go
  lib/utils/pull_request_test.go
Labels: Status: Review Needed

#1791 feat(dot/peerset): Implement peer scoring
  chain/dev/defaults.go
  chain/gssmr/defaults.go
  chain/kusama/defaults.go
  chain/polkadot/defaults.go
  cmd/gossamer/config.go
  dot/config.go
  dot/config/toml/config.go
  dot/core/interface.go
  dot/core/messages.go
  dot/core/messages_test.go
  dot/core/mocks/Network.go
  dot/core/test_helpers.go
  dot/network/config.go
  dot/network/connmgr.go
  dot/network/connmgr_test.go
  dot/network/discovery.go
  dot/network/discovery_test.go
  dot/network/host.go
  dot/network/host_test.go
  dot/network/mdns.go
  dot/network/mock_transaction_handler.go
  dot/network/notifications.go
  dot/network/service.go
  dot/network/service_test.go
  dot/network/state.go
  dot/network/sync.go
  dot/network/transaction.go
  dot/peerset/constants.go
  dot/peerset/errors.go
  dot/peerset/handler.go
  dot/peerset/peerset.go
  dot/peerset/peerset_test.go
  dot/peerset/peerstate.go
  dot/peerset/peerstate_test.go
  dot/peerset/test_helpers.go
  dot/rpc/modules/mocks/network_api.go
  dot/rpc/modules/system_test.go
  dot/sync/chain_sync.go
  dot/sync/chain_sync_test.go
  dot/sync/interface.go
  dot/sync/mocks/Network.go
  dot/sync/syncer.go
  lib/trie/proof_test.go
Labels: Status: Review Needed

#2000 chore(ci): no PR title and description check for dependabot
  .github/workflows/checks.yml
Labels: Status: Review Needed, ci, github_actions

#1977 maintenance: improve `*chainSync.determineSyncPeers`, add max worker retries
  dot/services.go
  dot/sync/chain_sync.go
  dot/sync/chain_sync_test.go
  dot/sync/syncer.go
  dot/sync/worker.go
Labels: Status: Review Needed

#1956 docs(issue): user story issue template
  .github/ISSUE_TEMPLATE/user_story.yml
Labels: Status: Review Needed

#1947 feat(lib/runtime): Implement `ext_offchain_http_request_start_version_1` host function
  lib/runtime/constants.go
  lib/runtime/offchain/httpset.go
  lib/runtime/offchain/httpset_test.go
  lib/runtime/types.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
  lib/runtime/wasmer/instance.go
Labels: runtime, Status: Review Needed

#1953 feat(flags): read log levels from flags
  cmd/gossamer/config.go
  cmd/gossamer/config_test.go
  cmd/gossamer/flags.go
Labels: Status: Review Needed

#1963 fix(dot/network): fix memory allocations with `sizedBufferPool`
  dot/network/notifications.go
  dot/network/pool.go
  dot/network/pool_test.go
  dot/network/service.go
Labels: Status: Review Needed

#2031 testing(lib/trie): change `lib/trie` slow and intensive benchmark-oriented tests to benchmarks
  lib/trie/test_utils.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2038 docs(contributing): document `make license` in contributing document
  .github/CONTRIBUTING.md
Labels: Status: Review Needed

#1994 feat(lib/runtime): Implement `ext_offchain_http_request_add_header_version_1` host function
  README.md
  lib/runtime/constants.go
  lib/runtime/offchain/httpset.go
  lib/runtime/offchain/httpset_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
Labels: runtime, Status: Review Needed

#2049 chore(trie): `lib/trie/hash.go` tests
  lib/trie/bytesBuffer_mock_test.go
  lib/trie/hash.go
  lib/trie/hash_test.go
  lib/trie/node.go
  lib/trie/node_mock_test.go
  lib/trie/node_test.go
  lib/trie/readwriter_mock_test.go
  lib/trie/writer_mock_test.go
Labels: Status: Review Needed

#2061 chore(mocks): lowercase mock file names
  dot/core/mocks/network.go
  dot/sync/mocks/network.go
Labels: Status: Review Needed

#2066 chore(httpserver): option to set shutdown timeout for unit tests
  internal/httpserver/option_test.go
  internal/httpserver/options.go
  internal/httpserver/run.go
  internal/httpserver/run_test.go
  internal/httpserver/server.go
  internal/httpserver/server_test.go
  internal/pprof/server.go
  internal/pprof/server_test.go
Labels: Status: Review Needed
