Repository ChainSafe/gossamer, pull requests merged in 2022-09, with the labels that each got.

#2805 fix(tests): fix block body regex in `TestChainRPC`
  tests/rpc/rpc_03-chain_test.go
Labels: Status: Review Needed, PR Easy

#2807 chore(ci): fix Deepsource issues
  dot/state/helpers_test.go
  dot/telemetry/mailer_test.go
  dot/types/block_test.go
  dot/types/body.go
  internal/log/patch_test.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/node_test.go
  lib/common/db_keys.go
  lib/crypto/sr25519/sr25519.go
  lib/genesis/helpers_test.go
  lib/runtime/wasmer/imports.go
  lib/transaction/priority_queue_test.go
  lib/trie/database_test.go
  lib/trie/helpers_test.go
  lib/trie/mem_test.go
  lib/trie/proof/helpers_test.go
  lib/trie/trie_test.go
  pkg/scale/decode_test.go
  pkg/scale/encode_test.go
  pkg/scale/result_example_test.go
  pkg/scale/varying_data_type_example_test.go
  pkg/scale/varying_data_type_test.go
Labels: Status: Review Needed, PR Easy

#2806 chore(dot): remove duplicate tests
  dot/build_spec_integration_test.go
  dot/sync/chain_sync_integration_test.go
Labels: PR Easy

#2790 chore(dot): remove unneeded error functions
  dot/core/errors.go
  dot/sync/errors.go
Labels: PR Easy

#2778 chore(config): improve `StateConfig`
  cmd/gossamer/config.go
  cmd/gossamer/flags.go
  dot/config.go
  dot/config/toml/config.go
Labels: PR Easy

#2830 chore(lib/trie): database.go small simplifications
  dot/state/storage.go
  lib/trie/database.go
  lib/trie/database_test.go
Labels: PR Easy

#2823 feat(wasmer): Add `SetTestVersion` method to `Config` struct
  lib/runtime/wasmer/config.go
  lib/runtime/wasmer/config_test.go
Labels: PR Easy

#2833 chore(lib/trie): `deleteNodesLimit` takes no `prefix`
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: PR Easy

#2804 chore(dot/state): `newTestStorageState` does not take `tries` argument
  dot/state/block_data_test.go
  dot/state/block_finalisation_test.go
  dot/state/block_notify_test.go
  dot/state/block_test.go
  dot/state/epoch_test.go
  dot/state/storage_notify_test.go
  dot/state/storage_test.go
Labels: PR Easy

#2786 fix(config): temporary fix for pprof enabled setting precedence
  chain/dev/config.toml
  chain/dev/defaults.go
  chain/gssmr/config.toml
  chain/gssmr/defaults.go
  chain/kusama/config.toml
  chain/kusama/defaults.go
  chain/polkadot/config.toml
  chain/polkadot/defaults.go
  cmd/gossamer/config.go
  dot/config.go
  dot/config_test.go
Labels: PR Easy

#2725 fix(trie): use direct Merkle value for database keys
  dot/state/offline_pruner.go
  dot/state/pruner/pruner.go
  dot/state/storage.go
  lib/runtime/storage/trie.go
  lib/trie/database.go
  lib/trie/trie.go
  lib/trie/trie_endtoend_test.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2810 chore(dot/sync): `handleJustification` returns errors
  dot/sync/chain_processor.go
  dot/sync/chain_processor_integration_test.go
  dot/sync/chain_processor_test.go
Labels: PR Easy

#2797 chore(types): `NewHeader` returns no error
  dot/core/helpers_test.go
  dot/digest/helpers_test.go
  dot/helpers_test.go
  dot/network/message_test.go
  dot/rpc/helpers_test.go
  dot/rpc/modules/chain_test.go
  dot/rpc/modules/helpers_test.go
  dot/state/helpers_test.go
  dot/state/service_test.go
  dot/state/storage_test.go
  dot/sync/bootstrap_syncer_integration_test.go
  dot/sync/chain_sync_test.go
  dot/sync/syncer.go
  dot/sync/syncer_integration_test.go
  dot/sync/syncer_test.go
  dot/sync/tip_syncer_integration_test.go
  dot/types/block_data_test.go
  dot/types/block_test.go
  dot/types/header.go
  dot/types/header_test.go
  lib/babe/build.go
  lib/babe/build_integration_test.go
  lib/babe/helpers_test.go
  lib/babe/verify_integration_test.go
  lib/grandpa/helpers_test.go
  lib/runtime/wasmer/exports_test.go
  lib/trie/genesis.go
  tests/utils/rpc/header.go
Labels: PR Easy

#2834 fix(lib/trie): prepare trie nodes for mutation only when needed
  internal/trie/node/subvalue.go
  internal/trie/node/subvalue_test.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2865 remove `digest type not supported` error
  dot/digest/digest.go
Labels: PR Easy
