Repository ChainSafe/gossamer, pull requests merged in 2022-10, with the labels that each got.

#2863 chore(dot/rpc/modules): narrower `TransactionStateAPI` interface
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/transaction_state_api.go
  dot/rpc/modules/system_integration_test.go
Labels: PR Easy

#2653 chore(lib/trie): split fuzz testing of the trie
  .github/workflows/fuzz.yml
  dot/state/helpers_test.go
  lib/trie/helpers_test.go
  lib/trie/trie_endtoend_test.go
Labels: Status: Review Needed, PR Easy

#2875 chore(lib/trie): `LoadFromMap` as function for transactional trie mutation
  dot/import.go
  dot/node_integration_test.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/genesis.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed, PR Easy

#2893 chore(Makefile): using `-ldflags="-s -w"` to shrinkg binary
  Makefile
Labels: PR Easy

#2809 fix(core): fix txn pool for latest runtime
  dot/core/errors.go
  dot/core/helpers_test.go
  dot/core/messages.go
  dot/core/messages_integration_test.go
  dot/core/messages_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/core/service_test.go
  dot/rpc/modules/author_integration_test.go
  lib/blocktree/hashtoruntime_test.go
  lib/blocktree/mocks_generate_test.go
  lib/blocktree/mocks_test.go
  lib/common/hasher.go
  lib/common/hasher_test.go
  lib/runtime/version.go
  lib/runtime/wasmer/exports.go
Labels: core, Status: Review Needed
