Repository ChainSafe/gossamer, pull requests merged in 2022-02, with the labels that each got.

#2091 tests(dot/rpc/modules): implement integration tests to rpc `author` module
  .gitignore
  dot/core/interface.go
  dot/core/mock_core_test.go
  dot/core/mocks/network_mock.go
  dot/core/mocks/storage_state_mock.go
  dot/core/service.go
  dot/network/helpers_test.go
  dot/network/service_test.go
  dot/rpc/modules/author.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/author_test.go
  dot/rpc/modules/childstate_test.go
  dot/state/transaction.go
  lib/runtime/constants.go
  lib/runtime/test_helpers.go
  lib/transaction/pool.go
  lib/transaction/priority_queue.go
Labels: tests, Status: Review Needed

#2274 fix(ci): mocks checking fixes
  .github/workflows/mocks.yml
Labels: Status: Review Needed

#2275 fix(ci): run golangci-lint with integration build tag
  .github/workflows/checks.yml
  Makefile
Labels: Status: Review Needed

#2287 fix(dot/state): inject mutex protected tries to states
  dot/rpc/modules/dev_integration_test.go
  dot/state/block.go
  dot/state/block_data_test.go
  dot/state/block_finalisation.go
  dot/state/block_finalisation_test.go
  dot/state/block_notify_test.go
  dot/state/block_race_test.go
  dot/state/block_test.go
  dot/state/epoch_test.go
  dot/state/helpers_test.go
  dot/state/initialize.go
  dot/state/offline_pruner.go
  dot/state/service.go
  dot/state/service_test.go
  dot/state/storage.go
  dot/state/storage_test.go
  dot/state/tries.go
  dot/state/tries_test.go
  lib/grandpa/grandpa_test.go
Labels: Status: Review Needed

#2291 fix(dot/network): resize bytes slice buffer if needed
  dot/network/helpers_test.go
  dot/network/inbound.go
  dot/network/notifications.go
  dot/network/service.go
  dot/network/sync.go
  dot/network/utils.go
Labels: Status: Review Needed

#2255 chore(lib/trie): refactor `trie.go` and fix additional memory problems
  internal/trie/node/branch.go
  internal/trie/node/branch_encode.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2301 chore(internal/trie/node): remove all mutexes
  internal/trie/node/branch.go
  internal/trie/node/copy.go
  internal/trie/node/hash.go
  internal/trie/node/leaf.go
  internal/trie/node/leaf_encode.go
Labels: Status: Review Needed

#2297 feat(lib/trie): clear fields when node is dirty
  internal/trie/node/dirty.go
  internal/trie/node/dirty_test.go
  internal/trie/node/leaf.go
  lib/trie/trie.go
Labels: Status: Review Needed

#2239 testing(dot/core): rewrite dot/core service tests (part 1)
  dot/core/errors.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/core/service_test.go
  tests/stress/helpers.go
  tests/stress/stress_test.go
Labels: core, tests, Status: Review Needed
