Repository ChainSafe/gossamer, pull requests merged in 2022-11, with the labels that each got.

#2871 fix(trie): `PopulateMerkleValues` behavior
  dot/state/offline_pruner.go
  lib/trie/database.go
  lib/trie/database_test.go
Labels: Status: Review Needed

#2929 fix(trie): remove encoding buffers pool
  internal/trie/node/branch_encode.go
  internal/trie/node/hash.go
  internal/trie/pools/pools.go
  lib/trie/trie.go
Labels: Status: Review Needed, PR Easy

#2759 chore(blockstate): change `GetRuntime` to take `common.Hash` as argument
  dot/core/helpers_test.go
  dot/core/interface.go
  dot/core/messages.go
  dot/core/messages_integration_test.go
  dot/core/mocks_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/core/service_test.go
  dot/rpc/modules/api.go
  dot/rpc/modules/mocks/block_api.go
  dot/rpc/modules/mocks_test.go
  dot/rpc/modules/payment.go
  dot/rpc/modules/payment_integration_test.go
  dot/rpc/modules/payment_test.go
  dot/rpc/modules/state_integration_test.go
  dot/services.go
  dot/state/block.go
  dot/state/test_helpers.go
  dot/sync/chain_processor.go
  dot/sync/chain_processor_integration_test.go
  dot/sync/chain_processor_test.go
  dot/sync/interface.go
  dot/sync/mocks_test.go
  lib/babe/babe.go
  lib/babe/babe_integration_test.go
  lib/babe/build_integration_test.go
  lib/babe/mock_state_test.go
  lib/babe/state.go
  lib/babe/verify_integration_test.go
  lib/grandpa/grandpa_test.go
Labels: PR Easy

#2832 chore(trie): `GetChangedNodeHashes` returns both inserted and deleted node hashes
  dot/state/storage.go
  lib/runtime/storage/trie.go
  lib/trie/database.go
Labels: Status: Review Needed, PR Easy

#2927 fix(trie): disallow empty byte slice node values
  internal/trie/node/copy.go
  internal/trie/node/decode_test.go
  internal/trie/node/encode.go
  internal/trie/node/encode_test.go
  internal/trie/node/subvalue.go
  internal/trie/node/subvalue_test.go
  lib/trie/trie.go
  lib/trie/trie_endtoend_test.go
Labels: Status: Review Needed

#2919 trie: no in-memory caching of node encoding
  internal/trie/node/copy.go
  internal/trie/node/copy_test.go
  internal/trie/node/dirty.go
  internal/trie/node/dirty_test.go
  internal/trie/node/encode.go
  internal/trie/node/encode_test.go
  internal/trie/node/hash.go
  internal/trie/node/hash_test.go
  internal/trie/node/node.go
  internal/trie/node/node_test.go
  lib/trie/database.go
  lib/trie/print_test.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2934 bug(lib/blocktree): fix blocktree highest common ancestor
  dot/core/interface.go
  dot/core/mocks_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/state/block.go
  lib/blocktree/blocktree.go
  lib/blocktree/blocktree_test.go
  lib/blocktree/node.go
  lib/grandpa/grandpa.go
  lib/grandpa/grandpa_test.go
  lib/grandpa/mocks_test.go
  lib/grandpa/state.go
Labels: Type: Bug

#2943 fix(trie): use cached Merkle values for root hash
  internal/trie/node/branch_encode.go
  lib/trie/buffer_mock_test.go
  lib/trie/helpers_test.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed, PR Easy

#2932 `TestAuthorModule_HasSessionKeys_Integration` does not data race anymore
  dot/rpc/modules/author_integration_test.go
Labels: PR Easy

#2922 chore(lib/trie): remove `Store` method
  dot/state/base_test.go
  dot/state/initialize.go
  dot/state/service.go
  dot/state/service_test.go
  lib/runtime/wasmer/imports_test.go
  lib/trie/database.go
  lib/trie/database_test.go
  lib/trie/proof/proof_test.go
  lib/trie/trie_endtoend_test.go
Labels: PR Easy

#2916 chore(trie): `Key` -> `PartialKey` for nodes
  dot/state/storage_test.go
  dot/state/tries_test.go
  internal/trie/node/branch_encode_test.go
  internal/trie/node/copy.go
  internal/trie/node/copy_test.go
  internal/trie/node/decode.go
  internal/trie/node/decode_test.go
  internal/trie/node/encode.go
  internal/trie/node/encode_decode_test.go
  internal/trie/node/encode_test.go
  internal/trie/node/hash_test.go
  internal/trie/node/header.go
  internal/trie/node/header_test.go
  internal/trie/node/node.go
  internal/trie/node/node_test.go
  lib/trie/database.go
  lib/trie/database_test.go
  lib/trie/genesis_test.go
  lib/trie/print_test.go
  lib/trie/proof/generate.go
  lib/trie/proof/generate_test.go
  lib/trie/proof/verify_test.go
  lib/trie/trie.go
  lib/trie/trie_endtoend_test.go
  lib/trie/trie_test.go
Labels: PR Easy

#2948 fix(dot): database close error checks
  dot/node.go
Labels: PR Easy

#2953 chore(wasmer): `nil` helper functions
  lib/runtime/wasmer/helpers.go
  lib/runtime/wasmer/imports.go
Labels: PR Easy

#2973 fix(wasmer): `ext_storage_exists_version_1` for empty values
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
Labels: PR Easy

#2954 chore(dot/state): rename `Set` method to `Put` to match trie method name
  dot/core/helpers_test.go
  dot/core/service_integration_test.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/childstate_integration_test.go
  dot/rpc/modules/childstate_test.go
  dot/rpc/modules/state_integration_test.go
  dot/rpc/modules/system_integration_test.go
  dot/state/storage_notify_test.go
  dot/state/storage_test.go
  dot/state/test_helpers.go
  lib/runtime/interface.go
  lib/runtime/storage/trie.go
  lib/runtime/storage/trie_test.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/helpers.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/imports_test.go
  lib/trie/child_storage.go
  lib/trie/child_storage_test.go
  lib/trie/database_test.go
Labels: PR Easy

#2971 fix(dot/sync): wrong error message at `checkOrGetDescendantHash`
  dot/sync/message.go
  dot/sync/message_test.go
Labels: PR Easy
