Repository ChainSafe/gossamer, pull requests merged in 2022-08, with the labels that each got.

#2691 fix(tests): handle node crash during waiting
  tests/utils/node/nodes.go
Labels: Status: Review Needed, PR Easy

#2724 chore(trie): Node `HashDigest` -> `MerkleValue`
  internal/trie/node/copy.go
  internal/trie/node/copy_test.go
  internal/trie/node/decode.go
  internal/trie/node/decode_test.go
  internal/trie/node/dirty.go
  internal/trie/node/dirty_test.go
  internal/trie/node/encode_decode_test.go
  internal/trie/node/hash.go
  internal/trie/node/hash_test.go
  internal/trie/node/node.go
  internal/trie/node/node_test.go
  lib/trie/database.go
  lib/trie/print_test.go
  lib/trie/proof/verify.go
  lib/trie/proof/verify_test.go
  lib/trie/trie.go
  lib/trie/trie_endtoend_test.go
  lib/trie/trie_test.go
Labels: Status: Review Needed, PR Easy

#2710 chore(dot/core): code substitution uses wasmer only
  dot/core/helpers_test.go
  dot/core/mocks_generate_test.go
  dot/core/mocks_runtime_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/core/service_test.go
  lib/runtime/wasmer/instance.go
Labels: Status: Review Needed

#2706 feat(monitoring): docker-compose.yml runs Gossamer + Prometheus + Grafana
  .dockerignore
  docker-compose.yml
  docker/grafana/grafana.ini
  docker/grafana/provisioning/dashboards/gossamer.json
  docker/grafana/provisioning/dashboards/gossamer.yml
  docker/grafana/provisioning/datasources/source.yml
  docker/prometheus/prometheus.yml
  docs/docs/integrate/using-prometheus.md
  internal/metrics/metrics.go
  prometheus.yml
Labels: Status: Review Needed

#2718 chore(ci): disable Codecov patch status
  codecov.yml
Labels: PR Easy

#2744 fix(ci): deepsource toml configuration
  .deepsource.toml
Labels: Status: Review Needed, PR Easy

#2729 chore(lint): upgrade to v1.48.0 and add linter `usestdlibvars`
  .golangci.yml
  Makefile
  dot/rpc/http_test.go
  dot/rpc/service_test.go
  dot/rpc/subscription/websocket.go
  internal/trie/node/hash_test.go
Labels: Status: Review Needed, PR Easy

#2736 lib/trie: add `Version` type
  lib/trie/version.go
  lib/trie/version_test.go
Labels: Status: Review Needed, PR Easy

#2687 chore(lib/runtime): `CheckRuntimeVersion` independent from existing runtime instance
  dot/core/mocks_runtime_test.go
  dot/rpc/subscription/listeners_test.go
  dot/state/block.go
  dot/sync/mock_instance_test.go
  lib/blocktree/mock_instance_test.go
  lib/runtime/interface.go
  lib/runtime/mocks/instance.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmer/instance_test.go
Labels: Status: Review Needed

#2751 chore(runtime): move `InstanceConfig` to `lib/runtime/wasmer`
  dot/core/helpers_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/rpc/http_test.go
  dot/rpc/modules/author_integration_test.go
  dot/rpc/modules/chain_integration_test.go
  dot/services.go
  dot/services_integration_test.go
  dot/services_test.go
  dot/state/block.go
  dot/state/initialize.go
  dot/sync/syncer_integration_test.go
  lib/babe/babe_integration_test.go
  lib/grandpa/grandpa_test.go
  lib/runtime/types.go
  lib/runtime/wasmer/config.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmer/test_helpers.go
Labels: PR Easy

#2673 chore(lib/runtime): refactor version struct and codec
  dot/core/messages_integration_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/core/service_test.go
  dot/rpc/modules/api_mocks.go
  dot/rpc/modules/mocks/core_api.go
  dot/rpc/modules/state.go
  dot/rpc/modules/state_test.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
  dot/state/block.go
  dot/state/block_notify_test.go
  lib/babe/build_integration_test.go
  lib/runtime/mocks/instance.go
  lib/runtime/mocks/version.go
  lib/runtime/test_helpers.go
  lib/runtime/version.go
  lib/runtime/version_test.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/imports.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmer/instance_test.go
Labels: Status: Review Needed

#2753 chore(mocks): remove unneeded generated mocks
  lib/grandpa/mocks/digest_handler.go
  lib/grandpa/mocks/network.go
Labels: PR Easy

#2752 fix(wasmer): error logs for signature verification
  lib/runtime/wasmer/imports.go
Labels: PR Easy

#2741 feat(pkg/scale): add `Encoder` with `Encode` method
  pkg/scale/encode.go
  pkg/scale/encode_test.go
  pkg/scale/varying_data_type_test.go
Labels: Status: Review Needed, PR Easy

#2743 chore(log): fix spelling and add padding for logger
  cmd/gossamer/config_test.go
  cmd/gossamer/flags.go
  cmd/gossamer/main.go
  dot/config_test.go
  internal/log/level.go
  internal/log/level_test.go
  internal/log/log.go
  internal/log/log_test.go
Labels: PR Easy

#2740 chore(dot/rpc): `NewStateRuntimeVersionResponse`
  dot/rpc/modules/state.go
  dot/rpc/subscription/listeners.go
  dot/rpc/subscription/listeners_test.go
Labels: PR Easy

#2756 fix(ci): run devnet unit tests in workflow
  .github/workflows/unit-tests.yml
  devnet/cmd/update-dd-agent-confd/main_test.go
Labels: PR Easy

#2773 chore(all): add leading space in exported comments
  dot/core/service.go
  dot/rpc/modules/state.go
  dot/state/storage_notify.go
  lib/babe/babe.go
  lib/crypto/keypair.go
Labels: PR Easy

#2747 feat(wasmer): get and cache state version in instance context
  dot/core/messages_integration_test.go
  dot/core/mocks_runtime_test.go
  dot/core/service.go
  dot/core/service_integration_test.go
  dot/state/block.go
  dot/sync/mock_instance_test.go
  lib/babe/build_integration_test.go
  lib/blocktree/mock_instance_test.go
  lib/runtime/interface.go
  lib/runtime/mocks/instance.go
  lib/runtime/test_helpers.go
  lib/runtime/types.go
  lib/runtime/version.go
  lib/runtime/version_test.go
  lib/runtime/wasmer/config.go
  lib/runtime/wasmer/exports.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/instance.go
  lib/runtime/wasmer/test_helpers.go
Labels: Status: Review Needed

#2779 chore(dot/network): log the errors from `stream.Close()`
  dot/network/helpers_test.go
  dot/network/light.go
  dot/network/notifications.go
  dot/network/notifications_test.go
  dot/network/stream_manager.go
  dot/network/sync.go
Labels: PR Easy

#2783 fix(dot/core): `RuntimeInstance` interface `Version` signature
  dot/core/interface.go
  dot/core/mocks_test.go
Labels: PR Easy

#2782 chore(dot/state): refactor `NewTries`
  dot/rpc/modules/dev_integration_test.go
  dot/state/initialize.go
  dot/state/offline_pruner.go
  dot/state/service.go
  dot/state/tries.go
  dot/state/tries_test.go
  lib/grandpa/grandpa_test.go
Labels: PR Easy

#2792 chore(all): fix test cases not pinned
  dot/core/service_test.go
  lib/runtime/wasmer/imports_test.go
Labels: PR Easy

#2791 chore(all): remove nil checks for constructors
  dot/core/errors.go
  dot/core/helpers_test.go
  dot/core/service.go
  dot/core/service_test.go
  dot/mock_node_builder_test.go
  dot/node.go
  dot/node_test.go
  dot/services.go
  dot/services_integration_test.go
  dot/services_test.go
  dot/sync/errors.go
  dot/sync/syncer.go
  dot/sync/syncer_test.go
  lib/babe/babe.go
  lib/babe/build.go
  lib/babe/build_integration_test.go
  lib/babe/errors.go
  lib/babe/verify.go
  lib/babe/verify_integration_test.go
  lib/babe/verify_test.go
  lib/blocktree/errors.go
  lib/grandpa/errors.go
  lib/grandpa/grandpa.go
  lib/grandpa/vote_message_test.go
Labels: PR Easy
