Repository ChainSafe/gossamer, pull requests merged in 2022-01, with the labels that each got.

#2141 chore(dot): remove trie related memory test
  dot/utils_test.go
Labels: tests, Status: Review Needed

#2108 chore(lib/trie): refactor `lib/trie/database.go`
  dot/state/offline_pruner.go
  lib/trie/database.go
  lib/trie/proof.go
Labels: trie, Status: Review Needed

#2140 fix(dot/network): public IP address logging
  dot/network/host.go
Labels: Type: Chore, Status: Review Needed

#2135 chore(codecov): change codecov.yml
  codecov.yml
Labels: Status: Review Needed

#2086 chore(lib/trie): node `Type() Type` method
  internal/trie/node/branch.go
  internal/trie/node/branch_test.go
  internal/trie/node/decode.go
  internal/trie/node/header.go
  internal/trie/node/leaf.go
  internal/trie/node/leaf_test.go
  internal/trie/node/node.go
  lib/trie/database.go
  lib/trie/lookup.go
  lib/trie/trie.go
Labels: trie, Status: Review Needed

#2136 chore(tests): unexport test helper functions from non `_test.go` files
  dot/build_spec.go
  dot/config_test.go
  dot/node_test.go
  dot/rpc/modules/dev_integration_test.go
  dot/rpc/modules/system_integration_test.go
  dot/services_test.go
  dot/utils.go
  dot/utils_test.go
  internal/trie/record/recorder_test.go
  lib/runtime/life/resolver_test.go
  lib/runtime/life/test_helpers.go
  lib/runtime/wasmer/exports_test.go
  lib/runtime/wasmer/test_helpers.go
  tests/utils/chain.go
  tests/utils/framework.go
  tests/utils/gossamer_utils.go
  tests/utils/header.go
  tests/utils/state.go
Labels: tests, Status: Review Needed

#2115 chore(lib/trie): use map for `trie.getInsertedNodeHashes` to reduce memory pressure
  dot/state/pruner/pruner.go
  dot/state/storage.go
  lib/runtime/storage/trie.go
  lib/trie/database.go
  lib/trie/trie.go
  lib/trie/trie_test.go
Labels: Status: Review Needed

#2081 chore(lib/trie): opportunist parallel hashing
  internal/trie/node/branch_encode.go
  internal/trie/node/branch_encode_test.go
Labels: trie

#2134 chore(test-skip-logs): Use `t.Log` + `fmt.Println` instead of `_, _ = fmt.Fprintln`
  tests/polkadotjs_test/start_polkadotjs_test.go
  tests/rpc/rpc_00_test.go
  tests/rpc/rpc_01-system_test.go
  tests/rpc/rpc_02-author_test.go
  tests/rpc/rpc_03-chain_test.go
  tests/rpc/rpc_04-offchain_test.go
  tests/rpc/rpc_05-state_test.go
  tests/rpc/rpc_06-engine_test.go
  tests/rpc/rpc_07-payment_test.go
  tests/rpc/rpc_08-contracts_test.go
  tests/rpc/rpc_09-babe_test.go
  tests/stress/stress_test.go
  tests/sync/sync_test.go
Labels: tests, Status: Review Needed

#2127 Jimmy/babe unit tests
  lib/babe/babe_integration_test.go
  lib/babe/build_integration_test.go
  lib/babe/crypto.go
  lib/babe/crypto_test.go
  lib/babe/epoch_integration_test.go
  lib/babe/errors.go
  lib/babe/mock_state_test.go
  lib/babe/secondary_integration_test.go
  lib/babe/secondary_test.go
  lib/babe/state.go
  lib/babe/verify.go
  lib/babe/verify_integration_test.go
  lib/babe/verify_test.go
Labels: tests, babe, Status: Review Needed

#2137 chore(tests): use `t.TempDir()`
  cmd/gossamer/account_test.go
  cmd/gossamer/config_test.go
  cmd/gossamer/export_test.go
  cmd/gossamer/flags_test.go
  cmd/gossamer/import_runtime_test.go
  cmd/gossamer/toml_config_test.go
  cmd/gossamer/utils.go
  dot/build_spec_test.go
  dot/config_test.go
  dot/import_test.go
  dot/network/block_announce_test.go
  dot/network/config_test.go
  dot/network/connmgr_test.go
  dot/network/discovery_test.go
  dot/network/gossip_test.go
  dot/network/host_test.go
  dot/network/light_test.go
  dot/network/mdns_test.go
  dot/network/notifications_test.go
  dot/network/service_test.go
  dot/network/transaction_test.go
  dot/network/utils_test.go
  dot/node_test.go
  dot/rpc/modules/system_integration_test.go
  dot/services_test.go
  dot/state/service_test.go
  dot/utils.go
  dot/utils_test.go
  lib/genesis/helpers_test.go
  lib/genesis/test_utils.go
  lib/keystore/encrypt.go
  lib/keystore/encrypt_test.go
  lib/keystore/helpers.go
  lib/keystore/helpers_test.go
  lib/utils/test_utils.go
  lib/utils/test_utils_test.go
  lib/utils/utils_test.go
Labels: Status: Review Needed

#2194 fix(dot/telemetry): telemetry hashes to be in the hexadecimal format
  dot/telemetry/afg_authority_set.go
  dot/telemetry/mailer_test.go
  lib/common/hash.go
Labels: Status: Review Needed

#2210 chore(lib/trie): add unit tests for `trie.go`
  internal/trie/node/branch.go
  internal/trie/node/copy.go
  internal/trie/node/copy_test.go
  internal/trie/node/decode.go
  internal/trie/node/decode_test.go
  internal/trie/node/encode_decode_test.go
  internal/trie/node/hash.go
  internal/trie/node/hash_test.go
  internal/trie/node/leaf.go
  lib/trie/buffer_mock_test.go
  lib/trie/helpers_test.go
  lib/trie/trie.go
  lib/trie/trie_endtoend_test.go
  lib/trie/trie_test.go
Labels: Status: Review Needed
