Repository ChainSafe/gossamer, pull requests merged in 2024-01, with the labels that each got.

#3694 chore(.github): update CODEOWNERS
  .github/CODEOWNERS
Labels: C-simple, S-doc

#3693 feat(config): dynamically set version based on environment
  Makefile
  cmd/gossamer/commands/version.go
  cmd/gossamer/commands/version_test.go
  config/config.go
  config/version.go
Labels: C-simple, S-cli

#3686 docs(docs/repo): add labels list to docs.
  .github/CONTRIBUTING.md
  .github/labels.yml
  .github/workflows/labels.yml
  docs/docs/repo/labels.md
Labels: C-simple, S-doc

#3702 Fix(cli): import-runtime
  cmd/gossamer/commands/import_runtime.go
Labels: C-simple, S-cli

#3695 fix(dot/sync): execute p2p handshake when there is no target
  dot/network/errors.go
  dot/network/light.go
  dot/network/notifications.go
  dot/network/request_response.go
  dot/network/service.go
  dot/network/stream_manager.go
  dot/network/sync.go
  dot/sync/chain_sync.go
  dot/sync/chain_sync_test.go
  dot/sync/errors.go
  dot/sync/interfaces.go
  dot/sync/mocks_test.go
  dot/sync/peer_view.go
Labels: S-network, P-high

#3698 chore(config): respect the xdg data home specification
  Dockerfile.staging
  chain/kusama/defaults.go
  chain/paseo/defaults.go
  chain/polkadot/defaults.go
  chain/westend-dev/defaults.go
  chain/westend-local/default.go
  chain/westend/defaults.go
  config/config.go
  config/toml.go
  devnet/alice.Dockerfile
  devnet/bob.Dockerfile
  docs/docs/usage/command-line.md
  docs/docs/usage/configuration.md
  docs/docs/usage/import-state.md
  dot/network/config.go
  go.mod
  go.sum
  lib/utils/utils.go
  lib/utils/utils_test.go
Labels: C-simple, S-cli, P-high

#3703 chore(chain): add telemetry and bootnodes
  chain/paseo/chain-spec-raw.json
Labels: C-simple, S-runtime

#3633 chore: break HandleConn test to batch of smaller more readable and maintainable
  dot/rpc/subscription/websocket.go
  dot/rpc/subscription/websocket_integration_test.go
Labels: P-low, C-simple, S-tests

#3707 chore(dot/parachain/overseer): fix `TestHandleBlockEvents` the flaky test
  dot/parachain/overseer/overseer.go
  dot/parachain/overseer/overseer_test.go
Labels: C-simple, S-subsystems-overseer, S-tests

#3600 feat(dot/parachain/backing): handle CanSecond incoming overseer message
  dot/parachain/backing/backing_implicit_view.go
  dot/parachain/backing/can_second.go
  dot/parachain/backing/can_second_test.go
  dot/parachain/backing/candidate_backing.go
  dot/parachain/backing/mocks_generate_test.go
  dot/parachain/backing/mocks_test.go
  dot/parachain/types/overseer_message.go
  dot/parachain/types/types.go
  go.mod
  go.sum
  tests/rpc/system_integration_test.go
Labels: S-subsystems-backing

#3640 feat(parachain/availabilitystore): implement database access functions for availability store subsystem
  .github/workflows/integration-tests.yml
  Dockerfile
  Makefile
  dot/parachain/availability-store/availability_store.go
  dot/parachain/availability-store/availability_store_test.go
  dot/parachain/availability-store/messages.go
  dot/parachain/availability-store/register.go
Labels: S-subsystems-availability

#3714 feat(tests/scripts): create script to retrieve trie state via rpc
  scripts/trie_state_script.go
  scripts/trie_state_script_test.go
Labels: S-tests, T-feat, S-sync-westend

#3708 chore: improve sync logs
  dot/state/block_finalisation.go
  dot/sync/chain_sync.go
  dot/sync/chain_sync_test.go
  dot/sync/syncer.go
  lib/grandpa/message_handler.go
Labels: C-simple, T-enhancement, P-high
